import { registerPage } from "@/lib/content/registry";
import type { ContentPage } from "@/lib/content/types";

const themePages: ContentPage[] = [
  {
    slug: "soft-life-birthday-theme",
    category: "themes",
    title: "Soft Life Birthday Theme (2026) — How to Plan an Effortlessly Beautiful Birthday",
    description: "Plan a soft life birthday theme with colors, decorations, outfit ideas, food, and activities that feel easy, elegant, and intentional.",
    headline: "Soft Life Birthday Theme",
    subheadline: "Luxury without the performance. Beauty without the stress.",
    tags: { vibe: "soft-life" },
    canonicalPath: "/birthday-themes/soft-life-birthday-theme",
    schemaType: "Article",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "Soft Life Birthday Theme", subheadline: "Luxury without the performance. Beauty without the stress." },
      { type: "paragraph", body: "A soft life birthday theme is about ease elevated. It's not cheap — but it's not loud either. Think linen tablecloths, muted florals, natural light, and the kind of food that's beautiful without trying. The aesthetic is intentional simplicity. The feeling is 'I don't need to prove anything.'" },
      {
        type: "palette-showcase",
        heading: "Soft Life Color Palette",
        palettes: [
          { name: "Quiet Luxury", mood: "understated, warm", colors: [{ hex: "#f5ebe0", name: "Cream" }, { hex: "#d5c4a1", name: "Wheat" }, { hex: "#c2b8a3", name: "Sand" }, { hex: "#a68a64", name: "Caramel" }, { hex: "#463f3a", name: "Espresso" }] },
        ],
      },
      {
        type: "idea-list",
        heading: "Soft Life Birthday Elements",
        ideas: [
          { title: "Setting", description: "Garden, courtyard, or a well-lit space with natural elements. No nightclubs. Think places with natural light and fresh air.", vibeTag: "soft-life" },
          { title: "Food", description: "Brunch energy. Fresh fruit, pastries, charcuterie, sparkling water, champagne. Catered or at a restaurant with a beautiful setting.", vibeTag: "soft-life" },
          { title: "Outfit", description: "Linen, silk, or knit. Neutral tones or one soft accent color. Comfortable enough to sit on the floor if the vibe goes there.", vibeTag: "soft-life" },
          { title: "Music", description: "Lo-fi, bossa nova, or an R&B playlist that doesn't spike the energy. The music should feel like background warmth.", vibeTag: "soft-life" },
          { title: "Activities", description: "No games. No itinerary. Maybe a group toast, a few photos, and the kind of conversation you can't have in a loud bar.", vibeTag: "soft-life" },
        ],
      },
      {
        type: "amazon-shop",
        title: "Set the Soft Life Mood",
        subtitle: "A handful of pieces that quietly do the heavy lifting.",
        placement: "soft-life-theme",
        format: "grid",
        items: [
          { query: "linen tablecloth neutral beige", label: "Linen Tablecloth", description: "Wrinkles are part of the aesthetic.", icon: "✦" },
          { query: "taper candles unscented natural", label: "Unscented Taper Candles", description: "Burn slow. Light honest.", icon: "☾" },
          { query: "dried pampas grass natural arrangement", label: "Dried Florals", description: "Pampas, wheat, bunny tails.", icon: "❋" },
          { query: "champagne flutes crystal stemless", label: "Crystal Coupes", description: "The toast is the moment.", icon: "◈" },
          { query: "essential oil diffuser ceramic minimalist", label: "Ceramic Diffuser", description: "Warm, quiet, barely there.", icon: "✧" },
          { query: "silk eye mask blackout", label: "Silk Eye Mask", description: "Morning-after protection.", icon: "☽" },
        ],
      },
      { type: "cta", headline: "Get your full birthday theme built for you", subheadline: "Our generator creates your colors, captions, and celebration plan based on your exact vibe.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "dark-feminine-birthday-theme",
    category: "themes",
    title: "Dark Feminine Birthday Theme (2026) — Mysterious, Powerful & Intentional",
    description: "Plan a dark feminine birthday theme with moody colors, ritual-inspired activities, dramatic aesthetics, and celebration ideas that embrace mystery and power.",
    headline: "Dark Feminine Birthday Theme",
    subheadline: "Not a party. A ritual.",
    tags: { vibe: "spiritual" },
    canonicalPath: "/birthday-themes/dark-feminine-birthday-theme",
    schemaType: "Article",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Dark Feminine Birthday Theme", subheadline: "Not a party. A ritual." },
      { type: "paragraph", body: "The dark feminine birthday theme is about reclaiming depth. It's not goth — it's intentional. Burgundy candles, low lighting, velvet textures, and the kind of celebration that feels like a scene from a film nobody's made yet. The vibe is powerful, mysterious, and unapologetically female. Think: Scorpio energy, black-tie meets witchcraft, the dinner party where everyone leaves feeling like they witnessed something." },
      {
        type: "palette-showcase",
        heading: "Dark Feminine Color Palette",
        palettes: [
          { name: "Obsidian Ceremony", mood: "dramatic, powerful", colors: [{ hex: "#1a0a0a", name: "Onyx" }, { hex: "#6b1a2a", name: "Oxblood" }, { hex: "#8b0000", name: "Deep Crimson" }, { hex: "#3d1a4e", name: "Midnight Plum" }, { hex: "#c9a96e", name: "Aged Gold" }] },
        ],
      },
      {
        type: "idea-list",
        heading: "Dark Feminine Birthday Elements",
        ideas: [
          { title: "Setting", description: "Candlelit spaces, private dining rooms, underground bars, or a dramatically lit home setting. Darkness is the aesthetic — use it. No bright venues.", vibeTag: "intimate" },
          { title: "Décor", description: "Black candles, dried flowers, velvet ribbons, gold accents. Fresh flowers in deep burgundy or black. A table that looks like it belongs in a renaissance painting.", vibeTag: "luxury" },
          { title: "Outfit", description: "Floor-length, structured, statement-making. Deep red, black, or midnight purple. One piece of real jewelry. The outfit should feel like armor and art simultaneously.", vibeTag: "luxury" },
          { title: "Activity", description: "A tarot or astrology reading, a ritual journaling session at midnight, or a private sound bath. Something that marks the birthday as a portal, not just a party.", vibeTag: "spiritual" },
          { title: "Music", description: "Lana Del Rey's deeper cuts, FKA Twigs, Sade, or a curated slow-burn R&B playlist. The music should feel like smoke — slow, atmospheric, enveloping.", vibeTag: "spiritual" },
        ],
      },
      {
        type: "amazon-shop",
        title: "Shop the Dark Feminine Aesthetic",
        subtitle: "Objects that set the scene without saying a word.",
        placement: "dark-feminine-theme",
        format: "grid",
        items: [
          { query: "black taper candles unscented set", label: "Black Taper Candles", description: "Lighting is the first ritual.", icon: "☾" },
          { query: "velvet tablecloth burgundy", label: "Velvet Tablecloth", description: "Heavy, deep, deliberate.", icon: "◈" },
          { query: "dried black rose arrangement", label: "Dried Black Roses", description: "Permanent. Theatrical.", icon: "❋" },
          { query: "crystal wine decanter smoke glass", label: "Smoke-Glass Decanter", description: "For the wine you actually chose.", icon: "✧" },
          { query: "brass incense holder minimalist", label: "Brass Incense Holder", description: "Scent is half the mood.", icon: "✦" },
          { query: "statement gold cocktail ring oversized", label: "Statement Ring", description: "One piece. Loud enough.", icon: "☽" },
        ],
      },
      { type: "cta", headline: "Get your dark feminine birthday experience built for you", subheadline: "Our generator creates your colors, captions, and celebration plan based on your exact vibe and zodiac.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "old-money-birthday-theme",
    category: "themes",
    title: "Old Money Birthday Theme (2026) — Quiet Luxury Birthday Aesthetic",
    description: "Plan an old money birthday theme with quiet luxury colors, understated elegance, timeless décor, and celebration ideas that feel inherited, not purchased.",
    headline: "Old Money Birthday Theme",
    subheadline: "Understated. Timeless. Impossibly elegant.",
    tags: { vibe: "luxury" },
    canonicalPath: "/birthday-themes/old-money-birthday-theme",
    schemaType: "Article",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Old Money Birthday Theme", subheadline: "Understated. Timeless. Impossibly elegant." },
      { type: "paragraph", body: "Old money doesn't announce itself — that's the point. An old money birthday theme is about restraint as a flex. Navy, cream, hunter green. Classic restaurants that have been open since 1987. A table that looks like it belongs in a colonial estate. No loud logos, no over-decorated cakes, no confetti cannons. Just exceptional quality, the right people, and an aesthetic that feels borrowed from a family portrait gallery." },
      {
        type: "palette-showcase",
        heading: "Old Money Color Palette",
        palettes: [
          { name: "Estate Library", mood: "timeless, inherited", colors: [{ hex: "#1c3a2a", name: "Hunter Green" }, { hex: "#1a2744", name: "Navy" }, { hex: "#c8b88a", name: "Camel" }, { hex: "#f5f0e8", name: "Ivory" }, { hex: "#8b6914", name: "Antique Gold" }] },
        ],
      },
      {
        type: "idea-list",
        heading: "Old Money Birthday Elements",
        ideas: [
          { title: "Setting", description: "Private dining rooms, members-only clubs, historic restaurants, or a well-appointed home. The setting should feel like it predates Instagram.", vibeTag: "luxury" },
          { title: "Table Setting", description: "Real silverware. Linen napkins. Flowers in a single color — all white, or deep green and white. No balloon arches. One large arrangement, centered.", vibeTag: "soft-life" },
          { title: "Dress Code", description: "Smart casual to black tie. Cashmere, blazers, loafers, silk. Nothing fast fashion. The aesthetic reward goes to the person who looks effortless.", vibeTag: "luxury" },
          { title: "Menu", description: "Classic dishes done exceptionally well. Oysters, steak, Dover sole, champagne. Order the wine properly. Let the sommelier do their job.", vibeTag: "luxury" },
          { title: "Gift Culture", description: "One thoughtful gift over ten forgettable ones. A first edition book, a cashmere something, or an experience. Old money is about curation, not quantity.", vibeTag: "intimate" },
        ],
      },
      { type: "cta", headline: "Get your old money birthday experience built for you", subheadline: "Our generator creates your palettes, captions, and celebration plan based on your exact vibe.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "y2k-birthday-theme",
    category: "themes",
    title: "Y2K Birthday Theme (2026) — Retro Futurism Birthday Aesthetic",
    description: "Plan a Y2K birthday theme with iridescent colors, chrome accents, early-2000s nostalgia, and party ideas that feel like the future that never happened.",
    headline: "Y2K Birthday Theme",
    subheadline: "Chrome. Iridescent. The future that never happened — but should have.",
    tags: { vibe: "turn-up" },
    canonicalPath: "/birthday-themes/y2k-birthday-theme",
    schemaType: "Article",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Y2K Birthday Theme", subheadline: "Chrome. Iridescent. The future that never happened — but should have." },
      { type: "paragraph", body: "Y2K birthday themes are having a full renaissance — and the aesthetic is deeper than just nostalgia. It's a specific visual language: iridescent fabrics, chrome surfaces, baby blue and hot pink together, frosted lips and butterfly clips. A Y2K birthday done right feels like stepping into a 2001 music video produced by someone with genuinely good taste. Playful, maximalist, and completely unafraid." },
      {
        type: "palette-showcase",
        heading: "Y2K Color Palette",
        palettes: [
          { name: "Millennium Shimmer", mood: "playful, futuristic", colors: [{ hex: "#a8d8ea", name: "Baby Blue" }, { hex: "#ff69b4", name: "Hot Pink" }, { hex: "#c0c0c0", name: "Chrome Silver" }, { hex: "#dda0dd", name: "Mauve Lilac" }, { hex: "#f5f5dc", name: "Iridescent Cream" }] },
        ],
      },
      {
        type: "idea-list",
        heading: "Y2K Birthday Elements",
        ideas: [
          { title: "Dress Code", description: "Low-rise, bedazzled, butterfly clips, platform sneakers, iridescent anything. The reference point is 2001 but the execution is 2026. Make it look intentional.", vibeTag: "turn-up" },
          { title: "Décor", description: "Mylar balloons, chrome table covers, disco balls, holographic banners. Everything should catch the light and throw it somewhere unexpected.", vibeTag: "turn-up" },
          { title: "Playlist", description: "Destiny's Child, early Britney, Jennifer Lopez, Christina Aguilera, Aaliyah — mixed with hyperpop and modern Y2K-influenced artists. The energy should be maximalist and unapologetic.", vibeTag: "turn-up" },
          { title: "Photo Ops", description: "Flip phone props, a Y2K photo booth backdrop, or a mirrored surface setup. The content should look like it came from a bedazzled camera phone circa 2002.", vibeTag: "turn-up" },
          { title: "Cake", description: "Chrome-effect fondant, holographic edible glitter, a cake that looks like a prop from TRL. The more maximalist, the more correct.", vibeTag: "turn-up" },
        ],
      },
      { type: "cta", headline: "Get your Y2K birthday experience built for you", subheadline: "Our generator creates your palettes, captions, and celebration plan based on your exact vibe and aesthetic.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "maximalist-birthday-theme",
    category: "themes",
    title: "Maximalist Birthday Theme (2026) — Dopamine Dressing & Bold Party Aesthetic",
    description: "Plan a maximalist birthday with bold colors, layered textures, dopamine dressing, and celebration ideas where more is always more.",
    headline: "Maximalist Birthday Theme",
    subheadline: "More color. More texture. More everything. That's the point.",
    tags: { vibe: "turn-up" },
    canonicalPath: "/birthday-themes/maximalist-birthday-theme",
    schemaType: "Article",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Maximalist Birthday Theme", subheadline: "More color. More texture. More everything. That's the point." },
      { type: "paragraph", body: "A maximalist birthday is a rejection of 'less is more' — and it's deeply, joyfully correct. The maximalist aesthetic is about layering: multiple patterns, unexpected color combinations, surfaces that shouldn't work but do, a table that looks like it took genuine vision to execute. If someone walks in and immediately says 'this is a lot,' you're doing it right. This isn't chaos — it's curated abundance." },
      {
        type: "palette-showcase",
        heading: "Maximalist Color Palette",
        palettes: [
          { name: "Curated Abundance", mood: "bold, layered, joyful", colors: [{ hex: "#e63946", name: "Fire Red" }, { hex: "#f4a261", name: "Tangerine" }, { hex: "#a8dadc", name: "Aqua" }, { hex: "#6a0572", name: "Royal Purple" }, { hex: "#ffd166", name: "Marigold" }] },
        ],
      },
      {
        type: "idea-list",
        heading: "Maximalist Birthday Elements",
        ideas: [
          { title: "Table Setting", description: "Multiple floral arrangements in contrasting heights. Patterned tablecloths under solid runners. Colored glassware. Mix the china patterns intentionally — it should look collected, not matched.", vibeTag: "luxury" },
          { title: "Outfit", description: "Pattern mixing, bold color blocking, statement jewelry, a bag that doesn't coordinate with anything but works anyway. Maximalism is fashion with a point of view.", vibeTag: "turn-up" },
          { title: "Cake", description: "Tall, layered, multiple tiers of different flavors and textures. Decorated with fruit, flowers, sprinkles, and at least one element that surprises. The cake is the centerpiece.", vibeTag: "turn-up" },
          { title: "Balloons", description: "Multiple sizes, multiple colors, arranged intentionally across the ceiling and walls. Not a balloon arch — a balloon environment. The room should feel full.", vibeTag: "turn-up" },
          { title: "Music", description: "A playlist that refuses genre consistency: Afrobeats into jazz into hyperpop into Motown into Samba. The maximalist playlist has range and doesn't apologize for it.", vibeTag: "turn-up" },
        ],
      },
      { type: "cta", headline: "Get your maximalist birthday experience built for you", subheadline: "Our generator creates your palettes, captions, and celebration plan based on your exact vibe.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
];

themePages.forEach(registerPage);
