import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | You The Birthday",
  description: "Terms and conditions for using You The Birthday.",
  robots: { index: false },
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-luxury">
      <div className="mx-auto max-w-3xl px-6 py-16 pb-24 space-y-8">
        <div className="space-y-3">
          <p className="text-[11px] uppercase tracking-[0.3em] text-champagne/50">Legal</p>
          <h1 className="heading-editorial text-3xl sm:text-4xl">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: April 14, 2026</p>
        </div>

        <div className="prose-luxury space-y-6 text-[15px] text-muted-foreground leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Service Description</h2>
            <p>You The Birthday ("the Service") is a personalized birthday experience generator. The Service uses artificial intelligence to create birthday titles, Instagram captions, color palettes, travel destination recommendations, celebration plans, restaurant suggestions, activity ideas, and astrology-informed profiles based on information you provide.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">AI-Generated Content</h2>
            <p>All personalized content is generated by artificial intelligence and is provided for entertainment and inspiration purposes. AI-generated content may contain inaccuracies, hallucinations, or outdated information. You are responsible for verifying any practical details (restaurant availability, travel advisories, health-related advice, etc.) independently.</p>
            <p>We do not guarantee the accuracy, completeness, or suitability of AI-generated content for any purpose.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Free and Paid Tiers</h2>
            <p><strong className="text-foreground/80">Free tier:</strong> One birthday generation per device, including identity, color palettes, captions, celebration style, and one destination preview. Additional free generations may be unlocked by providing an email address.</p>
            <p><strong className="text-foreground/80">Birthday Pass ($2.99 one-time):</strong> Unlocks the full birthday dashboard for the current session, including all destinations, restaurant recommendations, activities, and cosmic profile. Includes email delivery of the full report.</p>
            <p><strong className="text-foreground/80">Birthday Pro ($4.99/month):</strong> Unlimited generations, full dashboard access, and premium features. Subscription can be canceled at any time through the Stripe customer portal.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Payments and Refunds</h2>
            <p>Payments are processed securely by Stripe. By making a purchase, you agree to Stripe&apos;s terms of service.</p>
            <p>Due to the digital nature of the product, all sales are final. If you experience a technical issue that prevents delivery of your purchased content, contact us and we will resolve it or issue a refund.</p>
            <p>Monthly subscriptions can be canceled at any time. You will retain access until the end of your current billing period.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Circumvent generation limits through automated means or abuse.</li>
              <li>Use the service to generate harmful, illegal, or abusive content.</li>
              <li>Scrape, crawl, or systematically download content from the service.</li>
              <li>Resell or redistribute generated content as a competing service.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Intellectual Property</h2>
            <p>The content you generate through the Service is yours to use personally (social media posts, party planning, etc.). The Service&apos;s design, branding, content pages, and underlying technology remain the property of You The Birthday.</p>
            <p>Content on our editorial pages (captions, ideas, themes, etc.) is original and may not be reproduced in bulk without permission.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Limitation of Liability</h2>
            <p>The Service is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of AI-generated content, including but not limited to: inaccurate restaurant information, travel advice, or astrological interpretations.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">Contact</h2>
            <p>For questions about these terms, contact us at <strong className="text-foreground/80">legal@youthebirthday.app</strong>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
