import { registerPage } from "@/lib/content/registry";
import type { ContentPage } from "@/lib/content/types";

const destinationPages: ContentPage[] = [
  {
    slug: "luxury-birthday-destinations",
    category: "destinations",
    title: "Luxury Birthday Destinations (2026) — Where to Celebrate in Style",
    description: "Editorial guide to the best luxury birthday destinations — Amalfi, Dubai, Bali, Cape Town, Tokyo. How to pick, when to go, what to budget, who it's for.",
    headline: "Luxury Birthday Destinations",
    subheadline: "Your birthday should feel like the trip other people screenshot.",
    tags: { vibe: "luxury", destinationType: "category" },
    canonicalPath: "/birthday-destinations/luxury-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-23",
    sections: [
      { type: "hero", headline: "Luxury Birthday Destinations", subheadline: "Your birthday should feel like the trip other people screenshot." },
      {
        type: "paragraph",
        body: "A luxury birthday trip isn't about spending the most — it's about the feeling. The right destination makes it feel like the whole place was assembled for your weekend: the light, the food, the hotel, the pace. These are the cities, coastlines, and resorts that do that reliably — with notes on how to pick between them, what each one actually costs, and how to avoid turning a luxury trip into a logistics project.",
      },
      {
        type: "quick-take",
        heading: "Quick Take",
        rows: [
          { label: "Best for", value: "Milestone birthdays (30th, 40th, 50th), couples, close friend groups of 2–6." },
          { label: "Best seasons", value: "Shoulder seasons (May, September, early October) — peak weather without peak crowds or peak prices." },
          { label: "Budget reality", value: "$4k–$12k per person for 5–7 nights including flights, hotel, meals, and one standout experience." },
          { label: "Trip feel", value: "Slow mornings, reservation-worthy dinners, one private moment per day (boat, spa, driver, dinner at home)." },
          { label: "Avoid if", value: "You hate planning, travel with more than 8 people, or want pure beach-and-nothing-else — pick a wellness resort instead." },
        ],
      },
      {
        type: "destination-list",
        heading: "Ten Luxury Birthday Destinations",
        destinations: [
          { city: "Amalfi Coast", country: "Italy", description: "Cliffside hotels, lemon groves, private boat charters, and pasta that will ruin every other restaurant for you. Peak birthday destination for summer milestones where beauty is half the point.", bestFor: ["couples", "milestone birthdays", "groups of 4–8"], season: "summer" },
          { city: "Dubai", country: "UAE", description: "Skyscrapers, desert safaris, infinity pools, Michelin dinners, and a level of service that doesn't exist anywhere else. Does excess better than any destination on the planet.", bestFor: ["groups", "winter birthdays", "nightlife-forward trips"], season: "winter" },
          { city: "Bali", country: "Indonesia", description: "Villas with private pools and butlers, sunrise temple walks, world-class spas, and rice-terrace sunsets. Luxury meets spirituality without the price tag of Maldives.", bestFor: ["solo", "couples", "healing milestones"], season: "spring" },
          { city: "Cape Town", country: "South Africa", description: "Winelands, Table Mountain, ocean-facing suites in Camps Bay, and some of the best fine dining on earth at half the price of Europe. A birthday trip that doesn't feel predictable.", bestFor: ["adventure", "foodies", "groups"], season: "fall" },
          { city: "Tokyo", country: "Japan", description: "Omakase counters, Shibuya at night, Park Hyatt views, and a level of detail in everything — the wrapping, the plating, the signage — that makes luxury feel considered rather than loud.", bestFor: ["solo", "couples", "cultural depth"], season: "spring" },
          { city: "Santorini", country: "Greece", description: "Caldera-view suites, infinity pools carved into cliffs, private yachts at sunset. Smaller than Mykonos, quieter than Amalfi, every corner a photo.", bestFor: ["couples", "honeymoon-adjacent birthdays"], season: "summer" },
          { city: "Tulum", country: "Mexico", description: "Jungle hotels, cenote swims, beachfront omakase, and mezcal sunsets. Boho-luxury without the 12-hour flight — easiest luxury birthday for North American travelers.", bestFor: ["couples", "groups", "wellness"], season: "winter" },
          { city: "Marrakech", country: "Morocco", description: "Riads with tiled courtyards, rooftop pools, tagine dinners under string lights, and shopping in the medina that feels like a movie. A birthday where every dinner is the main event.", bestFor: ["groups of 4–6", "couples", "cultural travelers"], season: "fall" },
          { city: "Positano", country: "Italy", description: "The most photographed village on the Amalfi Coast, with cliff hotels, staircase dinners, and boats to Capri. A birthday trip that feels like a scene you're already inside.", bestFor: ["couples", "milestone birthdays"], season: "summer" },
          { city: "Kyoto", country: "Japan", description: "Ryokan stays with kaiseki dinners, private tea ceremonies, cherry-blossom or fall-foliage walks, and quiet that feels expensive on its own. The anti-Dubai luxury birthday.", bestFor: ["solo", "couples", "milestone reflection trips"], season: "spring" },
        ],
      },
      {
        type: "paragraph",
        heading: "Who a luxury birthday trip is actually for",
        body: "Luxury birthday trips land best for celebrants who want the memory more than the photos, and who already know what they like. If you're still figuring out whether you prefer cities or beaches, Europe or Asia, big groups or two people — a luxury budget on the wrong destination buys you regret at a premium. The strongest luxury birthdays are small (2–6 people), focused (one anchor experience — a sunset boat, a private dinner, an omakase), and mostly unscheduled in between.",
      },
      {
        type: "tip-list",
        heading: "How to choose between them",
        tips: [
          { title: "Start with the feeling, not the photo", body: "Santorini and Tokyo are both luxury — they feel nothing alike. Write down the three words you want the trip to feel (reflective / celebratory / soft / loud / sophisticated / adventurous) before you look at hotels." },
          { title: "Match the destination to the birthday month", body: "Amalfi in August is perfect; Amalfi in February is closed. Dubai in July is brutal; Dubai in January is ideal. A 'luxury trip' in the wrong season is a mid trip. Always book around climate." },
          { title: "Pick one splurge, not five", body: "The best luxury birthdays have one signature moment everyone will remember: a chartered boat, a Michelin birthday dinner, a private driver for a day, a spa takeover. Don't try to make every hour legendary — the contrast is what makes the splurge land." },
          { title: "Shorten the trip, lengthen the evenings", body: "Five nights in one city with long dinners beats ten nights racing between three. Luxury is density, not coverage." },
          { title: "Book early enough to choose", body: "Peak Amalfi, Santorini, and Mykonos hotels sell out by March for summer. Dubai sells out in December. Book 4–6 months ahead if you want the actual rooms the photos came from." },
        ],
      },
      {
        type: "paragraph",
        heading: "Budget reality, honestly",
        body: "A couples' luxury trip to Europe or Asia typically runs $6k–$10k per person for 5–7 nights (flights + hotel + meals + one standout experience). Same trip in Tulum or Marrakech: $3k–$5k per person. Dubai and the Maldives sit at the top at $10k–$15k+. You can get luxury-feeling under $4k per person if you're willing to fly shoulder-season, book a boutique hotel instead of a brand name, and limit the anchor experience to one dinner or one day.",
      },
      {
        type: "travel-inquiry-cta",
        eyebrow: "Plan it for me",
        headline: "Want this trip planned for you?",
        body: "If you'd rather not spend 40 hours researching hotels, we'll do it. Tell us the vibe, the budget, and the month — we'll come back with a shortlist + a complete plan, hand-built.",
        subject: "Luxury birthday trip inquiry",
      },
      { type: "cta", headline: "Or build the whole birthday here first", subheadline: "Our generator matches your vibe, age, and month to a destination + full celebration plan.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "amalfi-coast-birthday-trip",
    category: "destinations",
    title: "Amalfi Coast Birthday Trip (2026) — Complete Guide & Itinerary",
    description: "Everything you need for an Amalfi Coast birthday trip — where to stay (Positano vs Ravello), what to do, where to eat, and a sample 3-day itinerary.",
    headline: "An Amalfi Coast Birthday Trip, Planned Properly",
    subheadline: "Cliffside hotels, lemon groves, boat days. Here's how to do it right.",
    tags: { vibe: "luxury", season: "summer", destinationType: "city" },
    canonicalPath: "/birthday-destinations/amalfi-coast-birthday-trip",
    schemaType: "Article",
    publishStatus: "published",
    publishedAt: "2026-04-23",
    sections: [
      { type: "hero", headline: "An Amalfi Coast Birthday Trip, Planned Properly", subheadline: "Cliffside hotels, lemon groves, boat days. Here's how to do it right." },
      {
        type: "paragraph",
        body: "The Amalfi Coast is the birthday destination that even jaded travelers admit is worth it. The coastline is 30 miles of vertical towns — Positano, Praiano, Amalfi, Ravello, and a string of smaller villages — wedged between the cliffs and the sea. The food is better than you've been told. The hotel breakfasts alone justify the trip. And the light on the water, especially in the first and last hour of the day, is the kind of thing you'll still have photos of five years later.",
      },
      {
        type: "paragraph",
        body: "The trap is treating it as a rush-through. Two nights is not enough. Five nights, with one day that's entirely unscheduled, is the version that feels like a real trip instead of an Instagram loop. This guide is built around that: one anchor town, one boat day, long evenings, and a realistic sense of what things cost.",
      },
      {
        type: "quick-take",
        heading: "Quick Take",
        rows: [
          { label: "Best for", value: "30th, 40th, 50th milestone birthdays. Couples + small groups of 4–8." },
          { label: "Best season", value: "Late May–June or early September. Skip August — crowded, hot, crazy prices." },
          { label: "Budget", value: "$4k–$9k per person for 5 nights (flights + boutique hotel + meals + one boat day)." },
          { label: "Trip type", value: "Slow luxury. Long lunches. Boat days. Cliffside hotels. Not nightlife-forward." },
          { label: "Avoid if", value: "You want pure beach (water is rocky-entry, not Caribbean-flat), or travel with more than 8 people (roads are narrow, reservations are small)." },
        ],
      },
      {
        type: "paragraph",
        heading: "Why the Amalfi Coast works for birthdays",
        body: "Most luxury destinations ask you to choose between beauty, food, and comfort. Amalfi delivers all three without a compromise — the views are cinematic, the pasta is actually as good as the hype, and the hotels are run like a one-to-one relationship with you. For milestone birthdays especially, it has a quality most places don't: it rewards slowing down. You're not supposed to see everything. You're supposed to anchor in one town, take one boat day, eat three hours of dinner, and sleep well.",
      },
      {
        type: "tip-list",
        heading: "Where to anchor (the one call that shapes the trip)",
        tips: [
          { title: "Positano — for the postcard", body: "The most famous town. Colorful hotels stacked up the cliff, best-known beach clubs (Fornillo and Arienzo), the easiest boat access. Expensive, crowded in August, worth it for a first-time trip. Stay here if the photos matter." },
          { title: "Praiano — for the locals' version of Positano", body: "A 10-minute drive from Positano, quieter, still cliff-stacked, with better restaurants per capita and hotels like Casa Angelina and Hotel Margherita. Best pick for repeat visitors or couples who want calm with access." },
          { title: "Ravello — for the inland-quiet version", body: "High above the coast, with gardens, concert festivals in summer, and Hotel Caruso. The drive down to the water takes 25 minutes, but the views are the best on the coast. Stay here for a 40th or 50th where quiet matters." },
          { title: "Amalfi town — for the central hub", body: "Literally the town the coast is named for. Best ferry connections, easy walking, more restaurants in walking distance than anywhere else. Cheaper hotels than Positano with the same proximity to Capri day trips." },
        ],
      },
      {
        type: "tip-list",
        heading: "What to do (prioritized, not exhaustive)",
        tips: [
          { title: "Book one boat day, early in the trip", body: "A private boat charter (€800–€1,500 for 4–6 people, 6 hours) along the coast to Capri is the single experience that defines the trip. Stops at the Blue Grotto, swim stops in emerald coves, a long lunch at Da Gioia or Riccio on Capri. Do it on day 2 so weather flexibility exists if day 1 is off." },
          { title: "Walk the Path of the Gods", body: "A 4-mile trail from Bomerano to Nocelle with nonstop coast views. Take it slow, about 3 hours with photo stops. Best in May, June, or September when temperatures are under 80°F." },
          { title: "Lunch at Da Adolfo", body: "A beach-shack restaurant you can only reach by boat (10 minutes from Positano's main beach). Grilled fish on lemon leaves, house rosé in a chilled jug, feet in sand. Bookings open 2 weeks out — call, don't email." },
          { title: "Evening in Ravello", body: "Even if you're not staying there, drive up for sunset drinks at Villa Cimbrone's Infinity Terrace and dinner at Rossellinis. The 25-minute switchback drive back to Positano at night is its own memory." },
          { title: "One morning with nothing on the schedule", body: "Hotel breakfast on your balcony, swim in the hotel pool, a book, nowhere to be. Milestone birthdays need this day. Most people skip it and regret it." },
        ],
      },
      {
        type: "tip-list",
        heading: "Where to eat (the shortlist)",
        tips: [
          { title: "La Sponda (Positano)", body: "Inside Le Sirenuse. The dining room lit entirely by 400 candles. If the birthday dinner is one meal, make it this one. Book at the moment reservations open." },
          { title: "Da Gemma (Amalfi)", body: "Fresh pasta, whole fish, terrace table overlooking the main square. More casual than La Sponda, just as memorable. Easier reservation." },
          { title: "La Tagliata (Positano, above town)", body: "A family-run hillside place reached by a van they send down for you. Set menu, no options, house wine in pitchers, views for 40 miles. Best value-to-memory ratio on the coast." },
          { title: "Rossellinis (Ravello)", body: "Two-Michelin-star omakase-style tasting menu inside Hotel Caruso. Expensive, unhurried, for a milestone that wants the real thing." },
          { title: "Torre Normanna (Maiori)", body: "A watchtower turned restaurant, 20 minutes from Amalfi. Less famous, no waitlist, lunch overlooking the entire coast. Sleeper pick." },
        ],
      },
      {
        type: "paragraph",
        heading: "Style direction",
        body: "Amalfi photographs best in warm whites, ivory, sand, light lemon, pale denim. Leave anything black-tie-heavy at home — the coast is not a gala. Flat sandals for the cobblestone stairs (wedges are a trap), a light linen outfit for dinner, one piece of color to photograph against the white buildings. The aesthetic is 'quietly put together,' not 'resort-wear costume.'",
      },
      {
        type: "itinerary",
        heading: "A sample 5-day Amalfi birthday itinerary",
        subheading: "Anchored in Positano. Adjust by 1–2 days for longer or shorter trips.",
        days: [
          {
            title: "Day 1 — Arrive and settle",
            theme: "slow",
            activities: [
              { time: "Afternoon", label: "Transfer from Naples (90 min by private car)", description: "Arrive at the hotel by 4pm. Unpack slowly." },
              { time: "Evening", label: "Aperitivo at Franco's Bar", description: "Rooftop above Le Sirenuse. Sunset spritz to officially start the trip." },
              { time: "Dinner", label: "Simple dinner walking distance", description: "Pick a trattoria near the hotel. Day 1 isn't the splurge night — save the big meal for day 3." },
            ],
          },
          {
            title: "Day 2 — Boat day",
            theme: "the anchor experience",
            activities: [
              { time: "9am", label: "Private boat pickup from the Positano pier", description: "6 hours. Capri as the loop, Da Adolfo for lunch on the way back." },
              { time: "Mid-afternoon", label: "Swim stop at Arienzo or Laurito", description: "Lazy hour on water, boat drinks, back to Positano by 4." },
              { time: "Evening", label: "Low-key hotel dinner or room service", description: "After 6 hours of sun, the quiet evening is the reward." },
            ],
          },
          {
            title: "Day 3 — Birthday dinner",
            theme: "the main event",
            activities: [
              { time: "Morning", label: "Hotel pool + breakfast on the balcony" },
              { time: "Noon", label: "Walk down to Fornillo Beach", description: "Lunch at Da Ferdinando — pasta with clams, beach side, white wine." },
              { time: "Late afternoon", label: "Nap, get ready slowly", description: "This is the birthday night. Treat it like one." },
              { time: "Evening", label: "Dinner at La Sponda or Rossellinis", description: "Book 3 months ahead. Dress one level up. Order everything." },
            ],
          },
          {
            title: "Day 4 — Walk + village day",
            theme: "off-loop",
            activities: [
              { time: "Morning", label: "Path of the Gods hike — Bomerano to Nocelle", description: "3 hours with stops. Hotel packs lunch. Take the van back to Positano." },
              { time: "Afternoon", label: "Nap or hotel pool" },
              { time: "Evening", label: "Drive or taxi to Ravello for sunset", description: "Sundowners at Villa Cimbrone. Dinner at Belvedere or back in Positano." },
            ],
          },
          {
            title: "Day 5 — Slow morning, depart",
            theme: "reluctant",
            activities: [
              { time: "Morning", label: "One last hotel breakfast. Long." },
              { time: "Late morning", label: "One beach hour", description: "Short swim, one espresso, a few notes in your phone about what you don't want to forget." },
              { time: "Afternoon", label: "Transfer to Naples airport or extend to Rome" },
            ],
          },
        ],
      },
      {
        type: "travel-inquiry-cta",
        eyebrow: "Plan it for me",
        headline: "Want your Amalfi trip built end-to-end?",
        body: "Hotel shortlist in your budget, restaurant reservations booked 90 days out, boat day organized, transfers handled. You show up and have the trip.",
        subject: "Amalfi Coast birthday trip inquiry",
        destinationSlug: "amalfi-coast-birthday-trip",
      },
      { type: "cta", headline: "Or start with the full birthday plan", subheadline: "Generate a personalized birthday plan that includes Amalfi-style destinations, outfits, captions, and more.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "solo-birthday-destinations",
    category: "destinations",
    title: "Solo Birthday Destinations (2026) — Where to Celebrate Yourself",
    description: "The best solo birthday trip destinations — cities, retreats, and getaways for celebrating alone without feeling lonely.",
    headline: "Solo Birthday Destinations",
    subheadline: "A table for one. A whole world to yourself.",
    tags: { vibe: "solo" },
    canonicalPath: "/birthday-destinations/solo-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Solo Birthday Destinations", subheadline: "A table for one. A whole world to yourself." },
      { type: "paragraph", body: "Traveling alone on your birthday is not sad — it's a power move. These destinations are chosen specifically for solo travelers who want safety, walkability, great food, and the kind of atmosphere where being alone feels like freedom, not loneliness. Every city on this list has been picked for how it treats a person at a table for one." },
      {
        type: "destination-list",
        heading: "Best Solo Birthday Destinations",
        destinations: [
          { city: "Lisbon", country: "Portugal", description: "Tiled streets, rooftop bars, pastéis de nata for breakfast. Lisbon is the city that rewards the slow solo walker. It's affordable, beautiful, and full of people sitting alone at cafés without anyone thinking twice.", bestFor: ["solo", "foodie", "walkable", "budget-friendly"], season: "spring" },
          { city: "Kyoto", country: "Japan", description: "Temples, gardens, kaiseki dinners for one. Kyoto is built for solitude. The city moves at a pace that makes being alone feel meditative, not empty. Solo dining is not just accepted — it's the norm.", bestFor: ["solo", "cultural", "wellness", "peaceful"], season: "spring" },
          { city: "Marrakech", country: "Morocco", description: "Riads, rooftop sunsets, hammam rituals. Marrakech is sensory overload in the best way — solo travel here means you process everything at your own pace. The medina is a maze worth getting lost in alone.", bestFor: ["solo", "adventure", "cultural", "affordable"], season: "fall" },
          { city: "Copenhagen", country: "Denmark", description: "Design, bikes, hygge, and the world's best restaurants treating solo diners like VIPs. Copenhagen is where solo travel meets refined taste. Noma-adjacent restaurants regularly seat one.", bestFor: ["solo", "foodie", "design", "cultural"], season: "summer" },
          { city: "Sedona", country: "USA", description: "Red rocks, energy vortexes, spa retreats. Sedona is the American solo birthday for the person who wants to reconnect with themselves. Hike in the morning, spa in the afternoon, stargazing at night.", bestFor: ["solo", "wellness", "nature", "spiritual"], season: "fall" },
        ],
      },
      { type: "inline-cta", text: "Get solo destinations matched to your birthday month and vibe" },
      { type: "cta", headline: "Get your solo birthday planned", subheadline: "Our generator creates a complete birthday experience — destinations, captions, and celebration style — for the person celebrating on their own terms.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "beach-birthday-destinations",
    category: "destinations",
    title: "Beach Birthday Destinations (2026) — Celebrate by the Water",
    description: "The best beach birthday destinations worldwide — tropical islands, coastal cities, and waterfront escapes for every budget.",
    headline: "Beach Birthday Destinations",
    subheadline: "Sand, sun, and the sound of your birthday waves.",
    tags: { destinationType: "beach" },
    canonicalPath: "/birthday-destinations/beach-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Beach Birthday Destinations", subheadline: "Sand, sun, and the sound of your birthday waves." },
      { type: "paragraph", body: "A beach birthday is the celebration that requires the least planning and delivers the most relaxation. Whether you're looking for a private villa on a Thai island or a casual weekend at a US beach town, these destinations are chosen for their birthday energy — beautiful water, good food nearby, and the kind of setting where doing nothing feels like doing everything." },
      {
        type: "destination-list",
        heading: "Best Beach Birthday Destinations",
        destinations: [
          { city: "Tulum", country: "Mexico", description: "Jungle meets ocean. Cenotes, beachfront restaurants, mezcal sunsets. Tulum is where boho meets luxury and nobody has to choose. Close enough to the US for a long weekend, far enough to feel like an escape.", bestFor: ["beach", "couples", "groups", "wellness"], season: "winter" },
          { city: "Bali", country: "Indonesia", description: "Rice terraces, cliff-top bars, private pool villas under $200/night. Bali combines beach energy with spiritual depth. Your birthday can be a surf lesson in the morning and a temple ceremony at sunset.", bestFor: ["beach", "solo", "couples", "luxury"], season: "spring" },
          { city: "Zanzibar", country: "Tanzania", description: "White sand, turquoise water, Stone Town spice markets. Zanzibar is the unexpected beach destination that makes your birthday feel like a discovery. Affordable, stunning, and uncrowded.", bestFor: ["beach", "adventure", "affordable", "unique"], season: "summer" },
          { city: "Maui", country: "USA", description: "Volcanic beaches, whale watching, world-class resorts. Maui is the reliable luxury beach birthday — everything works, everything is beautiful, and the sunsets are the best in the US.", bestFor: ["beach", "luxury", "couples", "nature"], season: "spring" },
          { city: "Algarve", country: "Portugal", description: "Dramatic cliffs, hidden caves, golden beaches. The Algarve is Europe's best-kept beach secret — stunning coastline, great seafood, and a fraction of the cost of the French Riviera.", bestFor: ["beach", "budget-friendly", "groups", "foodie"], season: "summer" },
        ],
      },
      { type: "inline-cta", text: "Get beach destinations matched to your birthday season" },
      { type: "cta", headline: "Get your beach birthday planned", subheadline: "Our generator matches destinations to your birthday month, vibe, and budget.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "budget-birthday-destinations",
    category: "destinations",
    title: "Budget Birthday Destinations (2026) — Celebrate Without Breaking the Bank",
    description: "Affordable birthday trip destinations that still feel special — cities, beaches, and getaways that prove you don't need luxury prices for a luxury experience.",
    headline: "Budget Birthday Destinations",
    subheadline: "Expensive taste on a realistic timeline.",
    tags: { destinationType: "budget" },
    canonicalPath: "/birthday-destinations/budget-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Budget Birthday Destinations", subheadline: "Expensive taste on a realistic timeline." },
      { type: "paragraph", body: "A budget birthday trip is not a compromise — it's a strategy. Some of the most beautiful places in the world cost a fraction of what people assume. The trick is choosing destinations where your money stretches without your experience shrinking. These cities and regions give you great food, beautiful settings, and real culture without the luxury markup." },
      {
        type: "destination-list",
        heading: "Best Budget Birthday Destinations",
        destinations: [
          { city: "Mexico City", country: "Mexico", description: "World-class food scene, stunning architecture, incredible art, and you can eat like royalty for $15/day. Mexico City is the best-value city in the Western hemisphere for a birthday trip that feels rich.", bestFor: ["budget", "foodie", "cultural", "solo-friendly"], season: "spring" },
          { city: "Bangkok", country: "Thailand", description: "Street food that beats most restaurants, temples that stop time, and $40/night hotels that feel like $200. Bangkok is where budget travel feels like a lifestyle choice, not a limitation.", bestFor: ["budget", "adventure", "foodie", "nightlife"], season: "winter" },
          { city: "Porto", country: "Portugal", description: "Port wine tastings, riverside walks, blue-tiled buildings, and dinner for two under $30. Porto is the European birthday that doesn't require a European budget.", bestFor: ["budget", "romantic", "cultural", "walkable"], season: "spring" },
          { city: "Medellín", country: "Colombia", description: "Perfect weather, incredible coffee, vibrant neighborhoods, and a cost of living that makes every day feel generous. Medellín is the city where budget meets quality of life.", bestFor: ["budget", "adventure", "solo-friendly", "nightlife"], season: "winter" },
          { city: "Hoi An", country: "Vietnam", description: "Lantern-lit streets, custom tailoring, $3 bowls of pho, and beaches 20 minutes away. Hoi An is the birthday destination that feels like a fairy tale at budget prices.", bestFor: ["budget", "romantic", "beach", "cultural"], season: "spring" },
        ],
      },
      { type: "inline-cta", text: "Get budget-friendly destinations matched to your birthday" },
      { type: "cta", headline: "Get a birthday trip on your budget", subheadline: "Our generator finds destinations that match your vibe and budget — no luxury markup required.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
];

destinationPages.forEach(registerPage);
