import { registerPage } from "@/lib/content/registry";
import type { ContentPage } from "@/lib/content/types";

const destinationPages: ContentPage[] = [
  {
    slug: "luxury-birthday-destinations",
    category: "destinations",
    title: "Luxury Birthday Destinations (2026) — Where to Celebrate in Style",
    description: "The best luxury birthday trip destinations worldwide — from Amalfi to Dubai, Bali to Cape Town. Where to go when your birthday needs to feel expensive.",
    headline: "Luxury Birthday Destinations",
    subheadline: "Your birthday should look like the trip other people screenshot.",
    tags: { vibe: "luxury" },
    canonicalPath: "/birthday-destinations/luxury-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "Luxury Birthday Destinations", subheadline: "Your birthday should look like the trip other people screenshot." },
      { type: "paragraph", body: "A luxury birthday trip isn't about spending the most — it's about the feeling. The right destination makes you feel like the whole place was built for your weekend. These are the cities, coastlines, and hotels that do that." },
      {
        type: "destination-list",
        heading: "Best Luxury Birthday Destinations",
        destinations: [
          { city: "Amalfi Coast", country: "Italy", description: "Cliffside hotels, lemon groves, private boat charters, and pasta that will ruin you for every restaurant at home. The Amalfi Coast is birthday perfection for anyone who wants beauty with their luxury.", bestFor: ["couples", "milestone birthdays", "summer"], season: "summer" },
          { city: "Dubai", country: "UAE", description: "Skyscrapers, desert safaris, infinity pools, and restaurants where the check is a flex in itself. Dubai does excess better than anywhere.", bestFor: ["groups", "winter birthdays", "nightlife"], season: "winter" },
          { city: "Bali", country: "Indonesia", description: "Villas with private pools, sunrise temples, world-class spas, and the kind of beauty that makes you rethink everything. Luxury meets spirituality.", bestFor: ["solo", "couples", "healing"], season: "spring" },
          { city: "Cape Town", country: "South Africa", description: "Winelands, Table Mountain, ocean-facing suites, and some of the best fine dining in the world at half the price of Europe.", bestFor: ["adventure", "groups", "foodies"], season: "fall" },
          { city: "Mykonos", country: "Greece", description: "White-washed everything, beach clubs, sunset cocktails, and the energy of people who came to celebrate. Mykonos is a birthday in itself.", bestFor: ["groups", "summer", "nightlife"], season: "summer" },
          { city: "Tokyo", country: "Japan", description: "Omakase counters, Shibuya at night, onsen hotels, and a level of detail in everything that makes you feel like the whole city was curated. Tokyo is luxury for people with taste.", bestFor: ["solo", "couples", "cultural"], season: "spring" },
          { city: "Tulum", country: "Mexico", description: "Jungle hotels, cenotes, beachfront dinners, and mezcal sunsets. Tulum is where boho meets luxury and nobody has to choose.", bestFor: ["couples", "groups", "wellness"], season: "winter" },
        ],
      },
      { type: "cta", headline: "Get destination picks made for you", subheadline: "Our generator matches your vibe, budget, and birthday month to find destinations that fit.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "solo-birthday-destinations",
    category: "destinations",
    title: "Solo Birthday Destinations (2026) — Where to Celebrate Yourself",
    description: "The best solo birthday trip destinations — cities, retreats, and getaways for celebrating alone without feeling lonely.",
    headline: "Solo Birthday Destinations",
    subheadline: "A table for one. A whole world to yourself.",
    tags: { vibe: "solo" },
    canonicalPath: "/birthday-destinations/solo-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Solo Birthday Destinations", subheadline: "A table for one. A whole world to yourself." },
      { type: "paragraph", body: "Traveling alone on your birthday is not sad — it's a power move. These destinations are chosen specifically for solo travelers who want safety, walkability, great food, and the kind of atmosphere where being alone feels like freedom, not loneliness. Every city on this list has been picked for how it treats a person at a table for one." },
      {
        type: "destination-list",
        heading: "Best Solo Birthday Destinations",
        destinations: [
          { city: "Lisbon", country: "Portugal", description: "Tiled streets, rooftop bars, pastéis de nata for breakfast. Lisbon is the city that rewards the slow solo walker. It's affordable, beautiful, and full of people sitting alone at cafés without anyone thinking twice.", bestFor: ["solo", "foodie", "walkable", "budget-friendly"], season: "spring" },
          { city: "Kyoto", country: "Japan", description: "Temples, gardens, kaiseki dinners for one. Kyoto is built for solitude. The city moves at a pace that makes being alone feel meditative, not empty. Solo dining is not just accepted — it's the norm.", bestFor: ["solo", "cultural", "wellness", "peaceful"], season: "spring" },
          { city: "Marrakech", country: "Morocco", description: "Riads, rooftop sunsets, hammam rituals. Marrakech is sensory overload in the best way — solo travel here means you process everything at your own pace. The medina is a maze worth getting lost in alone.", bestFor: ["solo", "adventure", "cultural", "affordable"], season: "fall" },
          { city: "Copenhagen", country: "Denmark", description: "Design, bikes, hygge, and the world's best restaurants treating solo diners like VIPs. Copenhagen is where solo travel meets refined taste. Noma-adjacent restaurants regularly seat one.", bestFor: ["solo", "foodie", "design", "cultural"], season: "summer" },
          { city: "Sedona", country: "USA", description: "Red rocks, energy vortexes, spa retreats. Sedona is the American solo birthday for the person who wants to reconnect with themselves. Hike in the morning, spa in the afternoon, stargazing at night.", bestFor: ["solo", "wellness", "nature", "spiritual"], season: "fall" },
        ],
      },
      { type: "inline-cta", text: "Get solo destinations matched to your birthday month and vibe" },
      { type: "cta", headline: "Get your solo birthday planned", subheadline: "Our generator creates a complete birthday experience — destinations, captions, and celebration style — for the person celebrating on their own terms.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "beach-birthday-destinations",
    category: "destinations",
    title: "Beach Birthday Destinations (2026) — Celebrate by the Water",
    description: "The best beach birthday destinations worldwide — tropical islands, coastal cities, and waterfront escapes for every budget.",
    headline: "Beach Birthday Destinations",
    subheadline: "Sand, sun, and the sound of your birthday waves.",
    tags: { destinationType: "beach" },
    canonicalPath: "/birthday-destinations/beach-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Beach Birthday Destinations", subheadline: "Sand, sun, and the sound of your birthday waves." },
      { type: "paragraph", body: "A beach birthday is the celebration that requires the least planning and delivers the most relaxation. Whether you're looking for a private villa on a Thai island or a casual weekend at a US beach town, these destinations are chosen for their birthday energy — beautiful water, good food nearby, and the kind of setting where doing nothing feels like doing everything." },
      {
        type: "destination-list",
        heading: "Best Beach Birthday Destinations",
        destinations: [
          { city: "Tulum", country: "Mexico", description: "Jungle meets ocean. Cenotes, beachfront restaurants, mezcal sunsets. Tulum is where boho meets luxury and nobody has to choose. Close enough to the US for a long weekend, far enough to feel like an escape.", bestFor: ["beach", "couples", "groups", "wellness"], season: "winter" },
          { city: "Bali", country: "Indonesia", description: "Rice terraces, cliff-top bars, private pool villas under $200/night. Bali combines beach energy with spiritual depth. Your birthday can be a surf lesson in the morning and a temple ceremony at sunset.", bestFor: ["beach", "solo", "couples", "luxury"], season: "spring" },
          { city: "Zanzibar", country: "Tanzania", description: "White sand, turquoise water, Stone Town spice markets. Zanzibar is the unexpected beach destination that makes your birthday feel like a discovery. Affordable, stunning, and uncrowded.", bestFor: ["beach", "adventure", "affordable", "unique"], season: "summer" },
          { city: "Maui", country: "USA", description: "Volcanic beaches, whale watching, world-class resorts. Maui is the reliable luxury beach birthday — everything works, everything is beautiful, and the sunsets are the best in the US.", bestFor: ["beach", "luxury", "couples", "nature"], season: "spring" },
          { city: "Algarve", country: "Portugal", description: "Dramatic cliffs, hidden caves, golden beaches. The Algarve is Europe's best-kept beach secret — stunning coastline, great seafood, and a fraction of the cost of the French Riviera.", bestFor: ["beach", "budget-friendly", "groups", "foodie"], season: "summer" },
        ],
      },
      { type: "inline-cta", text: "Get beach destinations matched to your birthday season" },
      { type: "cta", headline: "Get your beach birthday planned", subheadline: "Our generator matches destinations to your birthday month, vibe, and budget.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "budget-birthday-destinations",
    category: "destinations",
    title: "Budget Birthday Destinations (2026) — Celebrate Without Breaking the Bank",
    description: "Affordable birthday trip destinations that still feel special — cities, beaches, and getaways that prove you don't need luxury prices for a luxury experience.",
    headline: "Budget Birthday Destinations",
    subheadline: "Expensive taste on a realistic timeline.",
    tags: { destinationType: "budget" },
    canonicalPath: "/birthday-destinations/budget-birthday-destinations",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Budget Birthday Destinations", subheadline: "Expensive taste on a realistic timeline." },
      { type: "paragraph", body: "A budget birthday trip is not a compromise — it's a strategy. Some of the most beautiful places in the world cost a fraction of what people assume. The trick is choosing destinations where your money stretches without your experience shrinking. These cities and regions give you great food, beautiful settings, and real culture without the luxury markup." },
      {
        type: "destination-list",
        heading: "Best Budget Birthday Destinations",
        destinations: [
          { city: "Mexico City", country: "Mexico", description: "World-class food scene, stunning architecture, incredible art, and you can eat like royalty for $15/day. Mexico City is the best-value city in the Western hemisphere for a birthday trip that feels rich.", bestFor: ["budget", "foodie", "cultural", "solo-friendly"], season: "spring" },
          { city: "Bangkok", country: "Thailand", description: "Street food that beats most restaurants, temples that stop time, and $40/night hotels that feel like $200. Bangkok is where budget travel feels like a lifestyle choice, not a limitation.", bestFor: ["budget", "adventure", "foodie", "nightlife"], season: "winter" },
          { city: "Porto", country: "Portugal", description: "Port wine tastings, riverside walks, blue-tiled buildings, and dinner for two under $30. Porto is the European birthday that doesn't require a European budget.", bestFor: ["budget", "romantic", "cultural", "walkable"], season: "spring" },
          { city: "Medellín", country: "Colombia", description: "Perfect weather, incredible coffee, vibrant neighborhoods, and a cost of living that makes every day feel generous. Medellín is the city where budget meets quality of life.", bestFor: ["budget", "adventure", "solo-friendly", "nightlife"], season: "winter" },
          { city: "Hoi An", country: "Vietnam", description: "Lantern-lit streets, custom tailoring, $3 bowls of pho, and beaches 20 minutes away. Hoi An is the birthday destination that feels like a fairy tale at budget prices.", bestFor: ["budget", "romantic", "beach", "cultural"], season: "spring" },
        ],
      },
      { type: "inline-cta", text: "Get budget-friendly destinations matched to your birthday" },
      { type: "cta", headline: "Get a birthday trip on your budget", subheadline: "Our generator finds destinations that match your vibe and budget — no luxury markup required.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
];

destinationPages.forEach(registerPage);
