import { registerPage } from "@/lib/content/registry";
import type { ContentPage } from "@/lib/content/types";

const ideaPages: ContentPage[] = [
  {
    slug: "30th-birthday-ideas",
    category: "ideas",
    title: "30th Birthday Ideas (2026) — How to Celebrate Turning 30",
    description: "The best 30th birthday ideas by vibe — luxury dinner, weekend trip, solo reset, group celebration, and more.",
    headline: "30th Birthday Ideas That Actually Match Your Energy",
    subheadline: "Turning 30 doesn't come with a manual. But it should come with a plan.",
    tags: { age: 30 },
    canonicalPath: "/birthday-ideas/30th-birthday-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "30th Birthday Ideas That Actually Match Your Energy", subheadline: "Turning 30 doesn't come with a manual. But it should come with a plan." },
      { type: "paragraph", body: "Your 30th birthday is the one people actually remember planning. Not because it has to be big — but because it should feel intentional. Whether you want a weekend away, a dinner that goes late, or a full solo reset, the best 30th birthday is the one that fits who you're becoming, not who you were." },
      {
        type: "idea-list",
        heading: "30th Birthday Ideas by Vibe",
        ideas: [
          { title: "Luxury birthday dinner", description: "Book the restaurant you've been saving for a reason. Private dining, tasting menu, dress code. This is your night.", vibeTag: "luxury", budgetTag: "$$$$" },
          { title: "Birthday weekend trip", description: "Pick a city you've never been to. Two nights, no agenda, just you and whoever you actually want there.", vibeTag: "adventure", budgetTag: "$$$" },
          { title: "Solo reset day", description: "Spa. Journal. Long walk. The gift of no one needing anything from you for 24 hours.", vibeTag: "solo", budgetTag: "$$" },
          { title: "Rooftop party with your people", description: "Rent a rooftop, curate the playlist, set the dress code. Small guest list, big energy.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Intimate dinner at home", description: "Cook or cater. Candles, wine, the 8 people who actually matter. Sometimes the table is the destination.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Adventure birthday", description: "Skydiving, surfing, hot air balloon. If you've been saying 'one day' — this is the day.", vibeTag: "adventure", budgetTag: "$$$" },
          { title: "Birthday photo shoot", description: "Hire a photographer. Pick a location that means something. Document this version of yourself.", vibeTag: "luxury", budgetTag: "$$" },
          { title: "Cultural experience", description: "Museum private tour, jazz night, art gallery opening, wine tasting. Feed your mind on your birthday.", vibeTag: "cultural", budgetTag: "$$" },
        ],
      },
      { type: "cta", headline: "Get a personalized birthday plan", subheadline: "Our generator builds a complete birthday experience based on your vibe, location, and style.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "soft-life-birthday-ideas",
    category: "ideas",
    title: "Soft Life Birthday Ideas (2026) — Celebrate Without the Chaos",
    description: "Soft life birthday ideas for people who want ease over excess — spa days, garden brunches, solo retreats, and gentle celebrations.",
    headline: "Soft Life Birthday Ideas",
    subheadline: "Your birthday should feel like exhaling.",
    tags: { vibe: "soft-life" },
    canonicalPath: "/birthday-ideas/vibe/soft-life-birthday-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "Soft Life Birthday Ideas", subheadline: "Your birthday should feel like exhaling." },
      { type: "paragraph", body: "Not every birthday needs a nightclub. Sometimes the most luxurious thing you can do is slow down. A soft life birthday is about ease, beauty, and the kind of joy that doesn't require recovery the next day." },
      {
        type: "idea-list",
        heading: "Soft Life Birthday Celebrations",
        ideas: [
          { title: "Spa day with your closest", description: "Massages, facials, robes, and zero small talk with strangers. Bring 2-3 people who understand silence.", vibeTag: "soft-life", budgetTag: "$$" },
          { title: "Garden brunch", description: "Flowers, linen, fresh juice, pastries. Set it up somewhere beautiful and eat slowly.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Cottage or cabin weekend", description: "Fire, blankets, wine, books. Let the location do the work.", vibeTag: "soft-life", budgetTag: "$$" },
          { title: "Sunrise birthday ritual", description: "Watch the sunrise on your birthday morning. Journal. Set your intention for the year. Then go get the best breakfast in your city.", vibeTag: "spiritual", budgetTag: "$" },
          { title: "Picnic in the park", description: "Charcuterie board, flowers, a Bluetooth speaker with taste. Effortless and beautiful.", vibeTag: "intimate", budgetTag: "$" },
        ],
      },
      { type: "cta", headline: "Get a soft life birthday plan made for you", subheadline: "Our generator builds a complete celebration based on ease, beauty, and your exact energy.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-dinner-ideas",
    category: "ideas",
    title: "Birthday Dinner Ideas (2026) — Where & How to Celebrate Over Food",
    description: "Birthday dinner ideas for every budget and group size — luxury restaurants, intimate home dinners, group outings, and themed dinner parties.",
    headline: "Birthday Dinner Ideas",
    subheadline: "The table is the destination.",
    tags: { celebrationType: "dinner" },
    canonicalPath: "/birthday-ideas/birthday-dinner-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    updatedAt: "2026-04-19",
    sections: [
      { type: "hero", headline: "Birthday Dinner Ideas", subheadline: "The table is the destination." },
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1543251660-ebb499e629bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=2400&utm_source=youthebirthday&utm_medium=referral",
        alt: "A candlelit birthday dinner table with wine glasses and warm lighting",
        caption: "The best birthday dinners are lit by candles, not ceiling lights.",
        credit: "Photo by Annie Spratt on Unsplash",
        creditUrl: "https://unsplash.com/@anniespratt?utm_source=youthebirthday&utm_medium=referral",
        ratio: "hero",
      },
      { type: "paragraph", body: "A birthday dinner is the one celebration format that works for almost everyone. Whether it's a tasting menu for two, a rowdy group night at a long table, or a beautifully catered meal at home — the dinner is where birthdays get real. These ideas are organized by how you want to feel, not just where you want to eat." },
      {
        type: "quick-take",
        rows: [
          { label: "Best for", value: "Milestone birthdays, intimate groups, people who want the night to feel planned" },
          { label: "Format", value: "Restaurant dinner, private dining, chef's table, dinner party at home" },
          { label: "Budget", value: "$100–$1,000+ depending on venue and group size" },
          { label: "Time needed", value: "3–14 days for a good reservation; more for private dining" },
          { label: "Avoid", value: "Choosing a place only because it photographs well" },
        ],
      },
      {
        type: "idea-list",
        heading: "Birthday Dinners by Vibe",
        ideas: [
          { title: "Private dining room at a great restaurant", description: "Call ahead. Ask for the private room. Tasting menu, wine pairing, your playlist playing softly. Let the restaurant do the work.", vibeTag: "luxury", budgetTag: "$$$$" },
          { title: "Long-table dinner with your people", description: "One long table, family-style dishes, bottles of wine, everyone talking over each other. The chaos is the point.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Themed dinner party at home", description: "Pick a cuisine. Set a dress code. Cook together or cater. Make it an experience, not just a meal.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Omakase or chef's counter for two", description: "No menu. No choices. Just sit down and let someone who's mastered their craft feed you something unforgettable.", vibeTag: "luxury", budgetTag: "$$$$" },
          { title: "Rooftop dinner with a view", description: "Find the restaurant with the best skyline view in your city. Book a table at sunset. Bring someone who appreciates silence.", vibeTag: "romantic", budgetTag: "$$$" },
          { title: "Birthday brunch instead", description: "Not everyone is a dinner person. A long birthday brunch with bottomless drinks, sunshine, and nowhere to be is its own kind of luxury.", vibeTag: "soft-life", budgetTag: "$$" },
          { title: "Potluck birthday dinner", description: "Everyone brings a dish that reminds them of you. The food tells a story. The cost is shared. The love is real.", vibeTag: "intimate", budgetTag: "$" },
          { title: "Solo birthday dinner", description: "Your favorite restaurant. A book or a journal. The best table. Sometimes the most powerful birthday move is taking yourself out.", vibeTag: "solo", budgetTag: "$$" },
        ],
      },
      { type: "inline-cta", text: "Want a birthday dinner plan matched to your city and vibe?" },
      {
        type: "tip-list",
        heading: "Birthday Dinner Tips",
        tips: [
          { title: "Book early and mention the birthday", body: "Most restaurants will do something small — a dessert, a candle, a better table — but only if they know." },
          { title: "Set the dress code even for casual dinners", body: "Saying 'wear something you feel good in' changes the energy of the whole night." },
          { title: "Don't split the bill publicly", body: "Either you're hosting (say so upfront) or someone else is. The check conversation kills the mood." },
        ],
      },
      { type: "inline-cta", text: "What to wear to your birthday dinner — outfit ideas by vibe →", href: "/blog/what-to-wear-birthday-dinner-outfit-ideas" },
      {
        type: "amazon-shop",
        title: "Birthday Table Picks",
        subtitle: "If you're hosting at home, these quietly make the table.",
        placement: "birthday-dinner-ideas",
        format: "grid",
        items: [
          { query: "linen napkins set of 12 neutral", label: "Linen Napkins", description: "A small upgrade you feel all night." },
          { query: "taper candle holders brass set", label: "Brass Candle Holders", description: "Instantly dresses up any table." },
          { query: "taper candles unscented beeswax", label: "Beeswax Taper Candles", description: "The light is the decor." },
          { query: "linen table runner neutral", label: "Linen Table Runner", description: "Anchors a long family-style table." },
          { query: "personalized cake topper acrylic", label: "Custom Cake Topper", description: "Name, age, or just a number." },
          { query: "wine glasses set of 6 crystal", label: "Crystal Wine Glasses", description: "Upgrade from the everyday glass." },
          { query: "champagne coupes set of 6 vintage", label: "Champagne Coupes", description: "Because the toast matters." },
          { query: "place card holders gold modern", label: "Place Cards", description: "Everyone has a seat. Literally." },
          { query: "menu card templates birthday dinner", label: "Printed Menu Cards", description: "Makes it feel like an event." },
          { query: "brass serving tray round", label: "Brass Serving Tray", description: "Use it all night. Keep it forever." },
        ],
      },
      {
        type: "inline-cta",
        text: "Pair your dinner with a theme that fits the room — Old Money, Dark Feminine, or Soft Life →",
        href: "/birthday-themes",
      },
      {
        type: "faq",
        heading: "Birthday Dinner FAQs",
        questions: [
          { question: "What's a good birthday dinner idea for adults?", answer: "The best birthday dinner for adults is one that matches the energy of the guest list. For small intimate groups, book a private dining room or a chef's counter. For bigger groups, reserve a long family-style table at a restaurant that doesn't rush you. Skip the themed chain-restaurant formats — adults remember the conversation and the food, not the balloons." },
          { question: "How do I plan a birthday dinner at home?", answer: "Pick a clear format (family-style, plated, or grazing), send the invite with a dress code (even a casual one), cook one thing well rather than everything adequately (or cater the mains and focus on table setup), and give yourself 90 minutes before guests arrive for candles, lighting, and a shower. The table is 70% of the impression — linen, real glasses, taper candles, not overheads." },
          { question: "What should I wear to a birthday dinner?", answer: "Match the venue's energy, then add one elevated element. For a casual restaurant, elevate with real jewelry or structured outerwear. For a nicer spot, lean into silk, satin, or tailoring. The birthday person is allowed to be the most dressed up in the room — that's the point." },
          { question: "How much should a birthday dinner cost?", answer: "A well-executed birthday dinner runs $40–$150 per person at a good restaurant, $150–$400 per person for private dining or omakase, and $20–$80 per person catered at home. The cost scales with the venue, not with how good the dinner feels. A long table at a mid-priced restaurant beats a mediocre dinner at a splashy one every time." },
          { question: "Is a birthday dinner better than a party?", answer: "For most adults past 25, yes. A dinner is intentional — a conversation, a clear start and end, actual food, and the chance to feel celebrated rather than just surrounded. A party is about volume and energy. Pick the format that matches what you want to remember about the night, not what looks better on social." },
        ],
      },
      { type: "cta", headline: "Get a personalized birthday dinner plan", subheadline: "Our generator recommends restaurants and celebration styles based on your city, vibe, and budget.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-trip-ideas",
    category: "ideas",
    title: "Birthday Trip Ideas (2026) — Where to Go for Your Birthday",
    description: "Birthday trip ideas by vibe, budget, and season — solo getaways, luxury escapes, adventure trips, group weekends, and romantic birthdays abroad.",
    headline: "Birthday Trip Ideas",
    subheadline: "The best birthday gift is a boarding pass.",
    tags: { celebrationType: "trip" },
    canonicalPath: "/birthday-ideas/birthday-trip-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Birthday Trip Ideas", subheadline: "The best birthday gift is a boarding pass." },
      { type: "paragraph", body: "A birthday trip is the celebration that keeps giving — weeks of anticipation, days of being somewhere new, and memories that last longer than any party. The trick is matching the trip to how you actually want to feel, not just where looks good on Instagram. These ideas are organized by energy, not just geography." },
      {
        type: "idea-list",
        heading: "Birthday Trips by Vibe",
        ideas: [
          { title: "Luxury beach escape", description: "Overwater villa, private beach, cocktails that arrive without asking. The birthday where you do absolutely nothing — beautifully.", vibeTag: "luxury", budgetTag: "$$$$" },
          { title: "City exploration weekend", description: "Pick a city with great food, walkable streets, and at least one restaurant you've been saving. Explore on foot. Eat everything.", vibeTag: "cultural", budgetTag: "$$$" },
          { title: "Adventure birthday", description: "Hiking, diving, zip-lining, surfing. The birthday where you prove to yourself that your best years aren't behind you.", vibeTag: "adventure", budgetTag: "$$" },
          { title: "Solo birthday retreat", description: "A cabin, a hot spring, a journal. No itinerary except what your body tells you. The trip where you remember who you are without other people's noise.", vibeTag: "solo", budgetTag: "$$" },
          { title: "Group villa trip", description: "Rent a villa or Airbnb with your people. Pool, kitchen, music, no plans. The trip that becomes the group chat name.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Romantic getaway for two", description: "Somewhere with good light, good wine, and no reason to check your phone. The trip where you reconnect.", vibeTag: "romantic", budgetTag: "$$$" },
          { title: "Road trip birthday", description: "Pick a direction. Three playlists. Two overnight stops. One rule: no GPS for the last hour.", vibeTag: "adventure", budgetTag: "$" },
          { title: "Wellness retreat", description: "Yoga, meditation, clean food, digital detox. The birthday where you invest in your next year's energy, not just this weekend's.", vibeTag: "healing", budgetTag: "$$$" },
        ],
      },
      { type: "inline-cta", text: "Get birthday destinations matched to your vibe and season" },
      {
        type: "tip-list",
        heading: "Birthday Trip Planning Tips",
        tips: [
          { title: "Book based on your birthday month, not just the destination", body: "A great destination in the wrong season is a disappointing trip. Match the timing to the weather." },
          { title: "Travel with people who match your energy", body: "A luxury traveler and a backpacker on the same birthday trip will both be miserable. Choose wisely." },
          { title: "Build in one unplanned day", body: "The best birthday trip moments happen when you have nowhere to be. Don't over-schedule." },
        ],
      },
      { type: "cta", headline: "Get birthday destinations matched to your vibe", subheadline: "Our generator recommends destinations based on your birthday month, celebration style, and budget.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-weekend-ideas",
    category: "ideas",
    title: "Birthday Weekend Ideas (2026) — How to Celebrate All Weekend",
    description: "Birthday weekend ideas for every style — staycations, mini trips, luxury weekends, group getaways, solo resets, and romantic escapes.",
    headline: "Birthday Weekend Ideas",
    subheadline: "One day is never enough.",
    tags: { celebrationType: "weekend" },
    canonicalPath: "/birthday-ideas/birthday-weekend-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Birthday Weekend Ideas", subheadline: "One day is never enough." },
      { type: "paragraph", body: "The best birthdays don't end at midnight. A birthday weekend gives you time to actually enjoy your celebration — not rush through it. Whether it's a local staycation, a nearby city trip, or a full group getaway, extending your birthday into a weekend changes the whole energy. Here's how to make it count." },
      {
        type: "idea-list",
        heading: "Birthday Weekend Ideas by Style",
        ideas: [
          { title: "Luxury hotel staycation", description: "Book the nicest hotel in your city. Order room service. Use the spa. Walk around your own city like a tourist with taste.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Nearby city weekend trip", description: "Drive 2-3 hours to a city you've never explored properly. One great dinner, one adventure, one lazy morning.", vibeTag: "adventure", budgetTag: "$$" },
          { title: "Birthday house rental", description: "Airbnb or VRBO with your closest friends. Groceries, board games, music, no agenda. The weekend where you just exist together.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Solo wellness weekend", description: "Friday: check in. Saturday: spa, hike, journal. Sunday: brunch, drive home slowly. You come back different.", vibeTag: "solo", budgetTag: "$$" },
          { title: "Birthday party weekend", description: "Friday dinner. Saturday event. Sunday brunch recovery. Three chances for people to show up.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Romantic weekend escape", description: "Cabin, beach house, or boutique hotel. Just the two of you. Cook together. Sleep in. Remember why you chose each other.", vibeTag: "romantic", budgetTag: "$$$" },
          { title: "Birthday camping trip", description: "Fire, stars, no signal. The birthday where you trade comfort for clarity. Bring good food and a warm sleeping bag.", vibeTag: "adventure", budgetTag: "$" },
          { title: "Cultural birthday weekend", description: "Plan around an event — a concert, exhibit opening, food festival, or show. Build the weekend around one unmissable moment.", vibeTag: "cultural", budgetTag: "$$" },
        ],
      },
      { type: "inline-cta", text: "Get a personalized birthday weekend plan with destinations and style" },
      {
        type: "tip-list",
        heading: "Birthday Weekend Tips",
        tips: [
          { title: "Protect Sunday morning", body: "Don't schedule anything before noon on the last day. The best part of a birthday weekend is waking up slowly." },
          { title: "Send a group text with the plan", body: "Even casual weekends need a shared doc or message. Times, addresses, what to bring. Reduce the 'what are we doing?' texts." },
          { title: "Budget for the experience, not just the place", body: "A mid-range hotel with a great dinner is better than a luxury hotel with room service pizza." },
        ],
      },
      { type: "cta", headline: "Get a personalized birthday weekend plan", subheadline: "Our generator creates a full celebration experience — destinations, style, and itinerary matched to you.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "solo-birthday-ideas",
    category: "ideas",
    title: "Solo Birthday Ideas (2026) — How to Celebrate Yourself, By Yourself",
    description: "Solo birthday ideas that feel empowering, not lonely — luxury self-dates, creative rituals, solo trips, reset days, and self-celebration that actually means something.",
    headline: "Solo Birthday Ideas",
    subheadline: "The most powerful birthday move is choosing yourself.",
    tags: { vibe: "solo" },
    canonicalPath: "/birthday-ideas/vibe/solo-birthday-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Solo Birthday Ideas", subheadline: "The most powerful birthday move is choosing yourself." },
      { type: "paragraph", body: "A solo birthday is not a consolation prize. It's a decision. Some of the most memorable birthdays happen when you stop performing for a group and start doing exactly what you want with zero compromise. These ideas are for the person who knows that being alone on your birthday can be the most intentional, luxurious, and honest way to celebrate." },
      {
        type: "idea-list",
        heading: "Solo Birthday Celebrations",
        ideas: [
          { title: "Luxury self-date", description: "Dress up. Go to the best restaurant you know. Bring a book or a journal. Order whatever you want. Sit at the bar if you prefer energy around you, or request the quietest table if you prefer peace.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Full reset day", description: "Spa morning. Long walk in the afternoon. Your favorite meal for dinner. No phone until evening. The birthday where you invest in your next year's energy.", vibeTag: "healing", budgetTag: "$$" },
          { title: "Solo birthday trip", description: "One bag, one destination, no itinerary. Pick somewhere you've been curious about and go alone. You'll meet yourself in a different city.", vibeTag: "adventure", budgetTag: "$$$" },
          { title: "Creative birthday ritual", description: "Write 30 things you learned this year. Make a playlist of one song per year you've been alive. Paint something. Build something. Create a birthday artifact that only you will understand.", vibeTag: "creative", budgetTag: "$" },
          { title: "Sunrise-to-sunset birthday", description: "Watch the sunrise. Spend the day doing one thing from each decade of your life. Watch the sunset. The whole arc of your day mirrors the whole arc of your years.", vibeTag: "spiritual", budgetTag: "$" },
          { title: "Hotel night for one", description: "Check into a hotel in your own city. Order room service. Take a bath. Watch something you'd never watch with someone else. The luxury of absolute solitude.", vibeTag: "luxury", budgetTag: "$$" },
          { title: "Birthday shopping spree", description: "Set a budget. Go to the stores you always walk past. Buy one thing that makes you feel like the person you're becoming, not the person you were.", vibeTag: "luxury", budgetTag: "$$" },
          { title: "Nature solo day", description: "Hike, swim, sit by water. Bring food. Leave your phone in the car for the hard part. The birthday where quiet becomes the gift.", vibeTag: "healing", budgetTag: "$" },
        ],
      },
      { type: "inline-cta", text: "Generate a solo birthday plan with your vibe, city, and energy" },
      {
        type: "tip-list",
        heading: "Solo Birthday Tips",
        tips: [
          { title: "Tell people in advance", body: "A solo birthday by choice feels different from one that looks like abandonment. Let your close people know you're choosing this. They'll respect it more." },
          { title: "Don't scroll on your birthday", body: "The fastest way to ruin a solo birthday is comparing it to someone else's party. Put the phone down until you're ready to post — if you post at all." },
          { title: "Do one thing you've been postponing", body: "Your birthday is permission to finally do the thing. Book the tattoo. Start the project. Sign up for the class. Use the day as a catalyst." },
        ],
      },
      { type: "cta", headline: "Get a solo birthday plan made for you", subheadline: "Our generator creates a personalized celebration based on your vibe, city, and the way you want to spend your own day.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "romantic-birthday-ideas",
    category: "ideas",
    title: "Romantic Birthday Ideas (2026) — How to Celebrate with Your Person",
    description: "Romantic birthday ideas for couples — intimate dinners, weekend getaways, at-home date nights, luxury experiences, and surprise moments that feel genuinely personal.",
    headline: "Romantic Birthday Ideas",
    subheadline: "The best birthday gift is presence.",
    tags: { vibe: "romantic" },
    canonicalPath: "/birthday-ideas/vibe/romantic-birthday-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Romantic Birthday Ideas", subheadline: "The best birthday gift is presence." },
      { type: "paragraph", body: "A romantic birthday isn't about grand gestures — it's about attention. The best ones feel like your partner actually thought about what you want, not what looks good. Whether you're planning for someone else or asking for what you need, these ideas prioritize intimacy over spectacle and connection over performance." },
      {
        type: "idea-list",
        heading: "Romantic Birthday Celebrations",
        ideas: [
          { title: "Candlelit dinner at home", description: "Cook together or order in from the best restaurant in town. Real candles, real plates, phone on silent. The intimacy of eating slowly with someone who sees you.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Surprise night away", description: "Book a hotel or cabin without telling them. Pack their bag. Drive somewhere beautiful. The surprise isn't the place — it's the effort.", vibeTag: "romantic", budgetTag: "$$$" },
          { title: "Recreate your first date", description: "Go back to where it started. Same restaurant, same neighborhood, same energy. Then show them how far you've come since.", vibeTag: "romantic", budgetTag: "$$" },
          { title: "Couples spa day", description: "Side-by-side massages. Steam room. Robes. Champagne. The birthday where you both get to exhale.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Rooftop sunset dinner", description: "Find the restaurant with the best view. Book the best table. Arrive at golden hour. Let the city do the backdrop work.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Love letter + one perfect experience", description: "Write something real. Then pair it with one thoughtful experience — a class, a concert, a private tour. The letter makes it personal. The experience makes it memorable.", vibeTag: "romantic", budgetTag: "$$" },
          { title: "Breakfast in bed, no agenda day", description: "Start with their favorite breakfast. Then let the day unfold. No reservations, no schedule, no 'we should go.' Just be together.", vibeTag: "intimate", budgetTag: "$" },
          { title: "Weekend getaway for two", description: "Cabin, beach house, or boutique hotel. Two nights, no friends, no family. The trip where you remember what it's like when it's just you two.", vibeTag: "romantic", budgetTag: "$$$" },
        ],
      },
      { type: "inline-cta", text: "Build a romantic birthday experience tailored to the two of you" },
      {
        type: "tip-list",
        heading: "Romantic Birthday Tips",
        tips: [
          { title: "Listen to what they've said all year", body: "The best romantic birthday isn't a surprise — it's proof you were paying attention. That restaurant they mentioned. That trip they hinted at. That thing they said they'd never buy themselves." },
          { title: "Presence over presents", body: "The most romantic gift is undivided attention. Put the phone away. Make eye contact. Ask questions you haven't asked in a while." },
          { title: "Don't plan every minute", body: "Romantic doesn't mean choreographed. Leave space for the unplanned moment — that's usually the one they remember." },
        ],
      },
      { type: "cta", headline: "Get a romantic birthday plan made for you", subheadline: "Our generator creates a personalized celebration built around intimacy, connection, and the two of you.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "summer-birthday-ideas",
    category: "ideas",
    title: "Summer Birthday Ideas (2026) — How to Celebrate When the Sun Is on Your Side",
    description: "Summer birthday ideas for every style — pool parties, rooftop dinners, beach trips, outdoor adventures, day parties, and warm-weather celebrations that feel effortless.",
    headline: "Summer Birthday Ideas",
    subheadline: "The sun showed up for your birthday. Now match the energy.",
    tags: { season: "summer" },
    canonicalPath: "/birthday-ideas/summer-birthday-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Summer Birthday Ideas", subheadline: "The sun showed up for your birthday. Now match the energy." },
      { type: "paragraph", body: "A summer birthday is a natural advantage. Longer days, warmer nights, and the kind of light that makes everything look good. Whether you're turning up at a pool party, having a quiet rooftop dinner, or disappearing to a beach for the weekend, summer gives you more room to celebrate without forcing it. These ideas are designed for the season — outdoor-first, warm-weather energy, no coats required." },
      {
        type: "idea-list",
        heading: "Summer Birthday Ideas by Vibe",
        ideas: [
          { title: "Rooftop dinner at golden hour", description: "Find the restaurant with the best sunset view. Book a table for 7pm. Wear something that catches the light. Let the sky do the decorating.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Pool or beach day party", description: "Floats, a Bluetooth speaker, coolers, and the 12 people who actually matter. The dress code is swimwear. The energy is unforced.", vibeTag: "turn-up", budgetTag: "$$" },
          { title: "Outdoor dinner party", description: "Long table in a backyard or park. String lights, candles, family-style food. The summer version of an intimate dinner — but with fireflies.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Beach weekend trip", description: "Rent a house near the water. Two nights, morning swims, evening grills, sand in everything. The birthday where you let summer do the planning.", vibeTag: "adventure", budgetTag: "$$$" },
          { title: "Sunset boat ride or cruise", description: "Charter a boat or book a sunset cruise. Even a kayak works. Being on water during golden hour is an automatic birthday upgrade.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Day party → night dinner", description: "Daytime at the pool or park. Evening at a restaurant you love. Two celebrations in one day, two energies, two outfits.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Solo sunrise-to-sunset day", description: "Start with a sunrise swim or walk. Spend the middle of the day doing exactly what you want. End with dinner outside, alone, watching the longest day of the year wind down.", vibeTag: "solo", budgetTag: "$" },
          { title: "Garden party or picnic", description: "Flowers, charcuterie, lemonade, linen. Set up in a beautiful outdoor space and let people come to you. Effortless and photogenic.", vibeTag: "soft-life", budgetTag: "$" },
          { title: "Adventure birthday", description: "Surfing, hiking, zip-lining, cliff jumping. Summer is the season for doing something that scares you a little. The birthday where you earn the story.", vibeTag: "adventure", budgetTag: "$$" },
        ],
      },
      {
        type: "tip-list",
        heading: "Summer Birthday Tips",
        tips: [
          { title: "Start earlier than you think", body: "Summer days are long. Start your celebration at 3 or 4pm instead of 7pm. You get golden hour, the sunset, and the transition to night — three vibes in one event." },
          { title: "Plan for heat", body: "Shade, water, lighter food, and a backup indoor option. Nobody celebrates well when they're overheating." },
          { title: "Use the natural light for photos", body: "The best summer birthday photos happen between 5-7pm. Schedule the 'group photo moment' during golden hour, not after dark." },
        ],
      },
      { type: "cta", headline: "Get a summer birthday plan made for you", subheadline: "Our generator creates destinations, celebration styles, and color palettes matched to your summer birthday energy.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "winter-birthday-ideas",
    category: "ideas",
    title: "Winter Birthday Ideas (2026) — How to Celebrate When the World Gets Quiet",
    description: "Winter birthday ideas for every mood — cozy dinners, cabin getaways, luxury indoor celebrations, glam parties, and warm-hearted winter celebrations.",
    headline: "Winter Birthday Ideas",
    subheadline: "The world slows down. Your birthday doesn't have to.",
    tags: { season: "winter" },
    canonicalPath: "/birthday-ideas/winter-birthday-ideas",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Winter Birthday Ideas", subheadline: "The world slows down. Your birthday doesn't have to." },
      { type: "paragraph", body: "A winter birthday comes with its own atmosphere — shorter days, longer nights, and the kind of mood that makes candles, fireplaces, and velvet feel right. The trick is leaning into the season instead of fighting it. Winter birthdays have a natural intimacy that summer ones can't touch. Use it. These ideas are designed for cold weather, warm rooms, and the energy that comes from celebrating in a season that rewards depth over spectacle." },
      {
        type: "idea-list",
        heading: "Winter Birthday Ideas by Vibe",
        ideas: [
          { title: "Candlelit dinner party", description: "Dim lights, heavy wines, rich food, a long table. Winter is the season for the kind of dinner where no one looks at their phone because the room is too good to leave.", vibeTag: "intimate", budgetTag: "$$$" },
          { title: "Cabin or lodge weekend", description: "Fire, snow, blankets, hot drinks. Bring your closest people or go alone. The cabin is the birthday. Everything else is atmosphere.", vibeTag: "soft-life", budgetTag: "$$$" },
          { title: "Luxury hotel night", description: "Check into the best hotel in your city. Order room service. Use the heated pool at midnight. Winter is when hotels feel most like an escape.", vibeTag: "luxury", budgetTag: "$$$$" },
          { title: "Winter glam party", description: "Velvet dress code. Champagne. Dark lipstick. The birthday party that feels like a scene from a film — moody, beautiful, and intentionally overdressed.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Spa and wellness day", description: "Hot stone massage, steam room, sauna, cold plunge if you're brave. Winter is the season your body needs to be taken care of. Make your birthday the start.", vibeTag: "healing", budgetTag: "$$" },
          { title: "Winter city trip", description: "Pick a city that's beautiful in winter — snow, markets, lights. Walk slowly. Eat in warm restaurants. Buy yourself something from a shop you'd never visit at home.", vibeTag: "adventure", budgetTag: "$$$" },
          { title: "Cozy movie night for two", description: "Projector, blankets, their favorite food, your favorite film. The most romantic winter birthday doesn't need a reservation.", vibeTag: "romantic", budgetTag: "$" },
          { title: "Birthday brunch then bookstore crawl", description: "Start with a long, warm brunch. Then walk through bookstores, vintage shops, or galleries. Winter birthdays reward the slow, wandering day.", vibeTag: "cultural", budgetTag: "$" },
          { title: "Solo winter reset", description: "Journal by the fire. Long bath. Early dinner. The birthday where you stop performing for the year and start listening to what you actually need.", vibeTag: "solo", budgetTag: "$" },
        ],
      },
      {
        type: "tip-list",
        heading: "Winter Birthday Tips",
        tips: [
          { title: "Lean into the darkness", body: "Winter birthdays look best in low light. Candles, warm lighting, and darker color palettes work better than trying to recreate summer brightness." },
          { title: "Overdress, always", body: "Winter is the only season where overdressing feels appropriate. Velvet, fur, silk, layers — your birthday outfit should feel like a character entrance." },
          { title: "Plan for coziness, not crowds", body: "Smaller guest lists feel better in winter. Intimate groups in warm rooms create the energy that big cold venues can't." },
        ],
      },
      { type: "cta", headline: "Get a winter birthday plan made for you", subheadline: "Our generator creates a personalized celebration matched to your winter mood, budget, and celebration style.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-ideas-for-her",
    category: "ideas",
    title: "Birthday Ideas for Her (2026) — Thoughtful, Stylish, Actually Good",
    description: "Birthday ideas for her that go beyond flowers and chocolate — spa days, surprise trips, luxury dinners, creative gifts, and celebrations she'll actually remember.",
    headline: "Birthday Ideas for Her",
    subheadline: "She deserves more than 'happy birthday' and a last-minute reservation.",
    tags: { celebrationType: "for-her" },
    canonicalPath: "/birthday-ideas/birthday-ideas-for-her",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    updatedAt: "2026-04-19",
    sections: [
      { type: "hero", headline: "Birthday Ideas for Her", subheadline: "She deserves more than 'happy birthday' and a last-minute reservation." },
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1652419476890-edbe7576760d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=2400&utm_source=youthebirthday&utm_medium=referral",
        alt: "A white cake topped with soft pink florals — a feminine birthday moment",
        caption: "The best birthday ideas for her are the ones she didn't have to ask for.",
        credit: "Photo by choose your stories on Unsplash",
        creditUrl: "https://unsplash.com/@chooseyourstories?utm_source=youthebirthday&utm_medium=referral",
        ratio: "hero",
      },
      { type: "paragraph", body: "Planning a birthday for her is not about spending the most money. It's about showing you paid attention. The best birthday ideas for her feel personal — like you actually thought about what she wants, not what's convenient. These ideas work whether you're planning for a partner, a sister, a mom, or a best friend. The common thread: effort that shows." },
      {
        type: "quick-take",
        rows: [
          { label: "Best for", value: "Stylish, personal, thoughtful birthdays that feel considered" },
          { label: "Format", value: "Dinner, spa day, trip, photoshoot, private experience, curated gift moment" },
          { label: "Budget", value: "Flexible — intention matters more than spend" },
          { label: "Time needed", value: "Same day to 2 weeks depending on the idea" },
          { label: "Avoid", value: "Generic girl-birthday clichés, forced pink, anything that ignores her actual taste" },
        ],
      },
      {
        type: "idea-list",
        heading: "Birthday Ideas for Her by Style",
        ideas: [
          { title: "Spa day she didn't have to plan", description: "Book it. Prepay it. Drive her there. The luxury isn't the massage — it's the fact that she didn't have to organize anything for once.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Surprise dinner at her favorite restaurant", description: "Not a new restaurant. HER restaurant. The one she always talks about. Book the best table. Invite the people she'd actually want there.", vibeTag: "intimate", budgetTag: "$$$" },
          { title: "Weekend getaway she didn't know about", description: "Pack her bag. Leave a note. Drive somewhere beautiful. The surprise isn't the destination — it's the proof that you planned ahead.", vibeTag: "romantic", budgetTag: "$$$" },
          { title: "Custom birthday box", description: "Her favorite snacks, a handwritten letter, something she mentioned wanting months ago, and one wildcard gift that shows you know her taste better than she thinks.", vibeTag: "intimate", budgetTag: "$$" },
          { title: "Birthday photo shoot", description: "Hire a photographer. Pick a location she loves. Let her feel beautiful and documented. This is the gift that becomes the memory.", vibeTag: "luxury", budgetTag: "$$" },
          { title: "Experience she's been postponing", description: "Pottery class, cooking class, helicopter ride, wine tasting — whatever she's said 'we should do that sometime' about. Make 'sometime' her birthday.", vibeTag: "adventure", budgetTag: "$$" },
          { title: "Flowers + a real letter + no expectations", description: "Not a Hallmark card. A real letter. What she means to you, specific memories, what you admire. This costs almost nothing and means everything.", vibeTag: "intimate", budgetTag: "$" },
          { title: "Full day off from responsibilities", description: "Take the kids. Handle the errands. Clean the house. Let her wake up to a day where nothing is expected of her. That's the real luxury.", vibeTag: "soft-life", budgetTag: "$" },
        ],
      },
      { type: "tip-list", heading: "Planning Tips", tips: [
        { title: "Ask her friends, not her", body: "She'll say 'I don't need anything.' Her friends know what she actually wants." },
        { title: "Effort beats expense", body: "A $30 gift you clearly thought about beats a $300 gift you panic-bought." },
        { title: "Handle the logistics", body: "The most common complaint about birthdays: 'I had to plan my own celebration.' Don't let that happen." },
      ]},
      {
        type: "amazon-shop",
        title: "Birthday Gift Ideas for Her",
        subtitle: "Things women actually keep, use, and mention later.",
        placement: "birthday-ideas-for-her",
        format: "grid",
        items: [
          { query: "silk pillowcase mulberry", label: "Silk Pillowcase", description: "She'll notice it every morning." },
          { query: "satin robe women short", label: "Satin Robe", description: "Morning-of-her-birthday essential." },
          { query: "personalized name necklace gold", label: "Name Necklace", description: "Name, initials, or a meaningful date." },
          { query: "pearl drop earrings gold plated", label: "Pearl Drop Earrings", description: "Elevated without feeling formal." },
          { query: "luxury bath set gift", label: "Luxury Bath Set", description: "The reset day, in a box." },
          { query: "kindle paperwhite", label: "Kindle Paperwhite", description: "For the reader in her life." },
          { query: "birthstone ring minimal", label: "Birthstone Ring", description: "Thoughtful. Actually wearable." },
          { query: "polaroid camera instant", label: "Polaroid Camera", description: "Document the day as it happens." },
          { query: "champagne glasses crystal set of 4", label: "Champagne Glasses", description: "The morning toast, done right." },
          { query: "vanity mirror with lights desktop", label: "Vanity Mirror", description: "Every morning feels like an occasion." },
        ],
      },
      {
        type: "inline-cta",
        text: "Match her birthday to a theme — Soft Life, Coquette, Garden Party →",
        href: "/birthday-themes",
      },
      {
        type: "faq",
        heading: "Birthday Ideas for Her FAQs",
        questions: [
          { question: "What is a good birthday idea for a girlfriend?", answer: "The best birthday idea for a girlfriend is one that shows you paid attention to what she actually likes — not what's conventionally romantic. A surprise dinner at her favorite spot with her closest friends beats a generic luxury gesture she didn't ask for. Pair one thoughtful gift (not five random ones) with one planned experience and a handwritten note. Effort and specificity matter more than spend." },
          { question: "What do you do for a birthday for her when you have no budget?", answer: "A low-budget birthday for her can feel more meaningful than an expensive one if the effort is visible. Cook her favorite meal, handmake a photo album of the year, plan a full day where she doesn't have to make a single decision, write a real letter describing what you admire about her. These cost almost nothing and beat a $300 last-minute gift every time." },
          { question: "What are luxury birthday ideas for her?", answer: "For a luxury birthday for her, think intentional access rather than flashy spending. Private dining at a chef-driven restaurant, a styled photoshoot, a weekend at a boutique hotel with a spa, a custom piece of jewelry from a small designer, or a personal shopping day with a stylist. The luxury is having someone curate the experience so she doesn't have to plan it herself." },
          { question: "What's a birthday idea for her that doesn't feel generic?", answer: "Skip the predictable — flowers alone, chocolate, a generic spa voucher, a brunch at a chain. Specific ideas that land: a workshop for a skill she mentioned (pottery, perfumery, pasta-making), a trip to a town she said she'd love to visit someday, a letter tied to a small meaningful object, or a dinner where her three favorite people from different circles all show up. Specificity reads as care." },
          { question: "How do I surprise her on her birthday?", answer: "Real surprises work when you build in plausible deniability (a reason she thinks she's going somewhere else) and layer small reveals rather than one big moment. Example: you tell her you're going to dinner nearby → you arrive at the airport instead → she finds her packed bag in the car → destination revealed at the gate. Three small surprises land better than one giant one." },
        ],
      },
      { type: "cta", headline: "Build a personalized birthday experience", subheadline: "Our generator creates a full birthday dashboard — titles, captions, palettes, destinations — tailored to her vibe.", buttonText: "Generate Her Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-ideas-for-him",
    category: "ideas",
    title: "Birthday Ideas for Him (2026) — Beyond Gift Cards and Steakhouses",
    description: "Birthday ideas for him that actually show effort — adventure days, luxury experiences, meaningful gifts, and celebrations he'll talk about for years.",
    headline: "Birthday Ideas for Him",
    subheadline: "He said he doesn't want anything. He's wrong.",
    tags: { celebrationType: "for-him" },
    canonicalPath: "/birthday-ideas/birthday-ideas-for-him",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    updatedAt: "2026-04-19",
    sections: [
      { type: "hero", headline: "Birthday Ideas for Him", subheadline: "He said he doesn't want anything. He's wrong." },
      {
        type: "image",
        src: "https://images.unsplash.com/photo-1696249680087-c29352cda5e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=2400&utm_source=youthebirthday&utm_medium=referral",
        alt: "A classic dining room with a set table and warm lighting — a refined birthday setting for him",
        caption: "Plan the night he'd plan for himself if he actually planned.",
        credit: "Photo by Praswin Prakashan on Unsplash",
        creditUrl: "https://unsplash.com/@praswin?utm_source=youthebirthday&utm_medium=referral",
        ratio: "hero",
      },
      { type: "paragraph", body: "Planning a birthday for him is tricky because he probably won't tell you what he wants. But that doesn't mean he doesn't want to be celebrated — it means he's not used to it. The best birthday ideas for him feel surprising but not over-the-top, thoughtful but not sentimental to the point of discomfort. These ideas work for partners, dads, brothers, and best friends who deserve more than a gift card." },
      {
        type: "quick-take",
        rows: [
          { label: "Best for", value: "Personal, low-pressure, experience-led birthdays" },
          { label: "Format", value: "Dinner, activity, trip, private hang, sports, grooming, music, food" },
          { label: "Budget", value: "Flexible — presence and planning matter more than spend" },
          { label: "Time needed", value: "1 day to 2 weeks depending on bookings" },
          { label: "Avoid", value: "Assuming every man wants whiskey, sports, cigars, or steak" },
        ],
      },
      {
        type: "idea-list",
        heading: "Birthday Ideas for Him by Style",
        ideas: [
          { title: "Adventure he wouldn't book for himself", description: "Go-kart racing, skydiving, a fishing charter, mountain biking, or a track day. The birthday where adrenaline replaces cake.", vibeTag: "adventure", budgetTag: "$$" },
          { title: "His dream dinner, fully handled", description: "Steakhouse, omakase, BBQ joint he's been eyeing — whatever his thing is. But you booked it, you invited people, you handled everything. He just showed up.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Tickets to something he'd never buy himself", description: "Courtside seats, concert VIP, a comedy show, a boxing match. The gift isn't the event — it's that you noticed what he gets excited about.", vibeTag: "turn-up", budgetTag: "$$$" },
          { title: "Gear upgrade he's been researching", description: "The headphones, the watch, the grill, the sneakers. Not a random 'nice thing' — the specific thing he's had in his cart for months.", vibeTag: "luxury", budgetTag: "$$$" },
          { title: "Day trip with zero agenda", description: "Drive somewhere new. No itinerary. Stop when something looks interesting. Eat at places you find along the way. The gift is unstructured time together.", vibeTag: "adventure", budgetTag: "$" },
          { title: "Whiskey/beer/wine tasting", description: "Not a basic bar crawl. A real tasting — distillery tour, brewery experience, or wine region visit. Pair it with good food and good conversation.", vibeTag: "cultural", budgetTag: "$$" },
          { title: "Surprise morning", description: "His favorite breakfast, his favorite music, no agenda until afternoon. Sometimes the best birthday gift for him is waking up to a day that was designed around his preferences, not a schedule.", vibeTag: "intimate", budgetTag: "$" },
          { title: "Group activity he'd never organize", description: "Poker night, pickup basketball, group golf outing, paintball. He won't plan it for himself but he'll love that you did.", vibeTag: "turn-up", budgetTag: "$$" },
        ],
      },
      { type: "tip-list", heading: "Planning Tips", tips: [
        { title: "Don't ask him what he wants", body: "He'll say 'nothing' or 'I don't care.' Pay attention to what he talks about, what he browses, what he says he'll 'get around to.'" },
        { title: "Experience over object", body: "Most guys have enough stuff. Give him a memory instead. Something he'll reference months later." },
        { title: "Include his people", body: "A lot of guys don't get celebrated by their friends. Organizing his friends to show up is often the most meaningful part." },
      ]},
      {
        type: "amazon-shop",
        title: "Birthday Gift Ideas for Him",
        subtitle: "The kind of things he wouldn't buy himself but absolutely uses.",
        placement: "birthday-ideas-for-him",
        format: "grid",
        items: [
          { query: "leather dopp kit men travel", label: "Leather Dopp Kit", description: "For the trips he says he'll take." },
          { query: "cocktail glasses rocks set of 4", label: "Cocktail Glasses", description: "Heavy base. Feels like something." },
          { query: "leather bifold wallet minimal", label: "Leather Wallet", description: "Replacing the one he's had since college." },
          { query: "cocktail making set home bar", label: "Cocktail Kit", description: "Upgrade the home bar in one move." },
          { query: "wireless speaker bluetooth portable", label: "Bluetooth Speaker", description: "Works on the patio, the kitchen, the trip." },
          { query: "grooming kit beard men premium", label: "Grooming Kit", description: "A quiet upgrade to his routine." },
          { query: "leather weekender bag men", label: "Weekender Bag", description: "For the trips he says he'll take." },
          { query: "leather card holder men minimal", label: "Card Holder", description: "The pared-down everyday upgrade." },
          { query: "brass valet tray mens", label: "Valet Tray", description: "A home for the watch, the keys, the ring." },
          { query: "vinyl record storage shelf wood", label: "Record Storage", description: "For the collection he's rebuilding." },
        ],
      },
      {
        type: "inline-cta",
        text: "Give the birthday a vibe — pair with Old Money, Maximalist, or Disco themes →",
        href: "/birthday-themes",
      },
      {
        type: "faq",
        heading: "Birthday Ideas for Him FAQs",
        questions: [
          { question: "What is a good birthday idea for a boyfriend?", answer: "The best birthday ideas for a boyfriend skip the generic gifts and focus on experiences that reflect his actual interests. Book the activity he's mentioned but never scheduled, organize the dinner where his three best friends all show up, or plan a day with zero agenda where he gets to decide everything in real time. Most men don't get organized around them — be the person who makes it happen." },
          { question: "What do you get a man who says he wants nothing?", answer: "He says 'nothing' because he's uncomfortable being the center of attention, not because he doesn't want to be celebrated. Skip asking him directly — pay attention to what he mentions, what he browses, what he says he'll 'get around to.' The gift is proof you listened. A book he said he wanted to read, a headlamp for the camping trip he keeps mentioning, tickets to the comedy show he linked in a group chat — specificity beats price." },
          { question: "What's a good birthday activity for him?", answer: "Activities that land: a day trip he wouldn't book himself (racing, fishing charter, distillery tour), an event he'd enjoy but never planned around (concert, comedy show, boxing match), or an unstructured day where you handle the logistics (drive somewhere new, eat at places you find, no itinerary). Experiences beat objects for most adult men." },
          { question: "What do you get a guy who has everything?", answer: "The trick isn't to find a better object — it's to find an experience or an upgrade to something he already uses daily. Better version of his current watch, a signed copy of the book he loves, a tailored shirt that actually fits, a track day in the car he's been saving for, or a weekend trip to the city he keeps saying he wants to revisit. Upgrade the daily, not the novelty." },
          { question: "Should I throw him a party or plan a dinner?", answer: "Dinner is almost always the better move for adult men. Parties require him to host energy; a dinner lets him receive it. Book a private room or long table at a restaurant he'd actually pick, invite 6–12 people he genuinely cares about, and make sure someone gives a toast. The format feels intentional without demanding performance." },
        ],
      },
      { type: "cta", headline: "Build a personalized birthday experience", subheadline: "Our generator creates a full birthday dashboard — titles, captions, palettes, destinations — tailored to his vibe.", buttonText: "Generate His Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
];

ideaPages.forEach(registerPage);
