import { registerPage } from "@/lib/content/registry";
import type { ContentPage } from "@/lib/content/types";

const captionPages: ContentPage[] = [
  {
    slug: "30th-birthday-captions",
    category: "captions",
    title: "30th Birthday Captions for Instagram (2026) — Dirty 30, Flirty 30 & More",
    description: "The best 30th birthday Instagram captions for every vibe — hype, soft life, funny, luxe, and reflective. Copy and post.",
    headline: "30th Birthday Captions for Instagram",
    subheadline: "Thirty looks different on everybody. Here's how to caption yours.",
    tags: { age: 30 },
    canonicalPath: "/birthday-captions/30th-birthday-captions",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      {
        type: "hero",
        headline: "30th Birthday Captions for Instagram",
        subheadline: "Thirty looks different on everybody. Here's how to caption yours.",
      },
      {
        type: "paragraph",
        body: "Turning 30 is the birthday that actually means something. It's not just another year — it's the line between figuring it out and starting to live like you already did. Whether you're going full glam, keeping it low key, or somewhere in between, your caption should match the energy. We wrote these so you don't have to.",
      },
      {
        type: "caption-list",
        heading: "The Best 30th Birthday Captions",
        categories: [
          {
            name: "Hype & Confident",
            captions: [
              "30 and I'm just getting started. You're not ready.",
              "Dirty thirty with clean intentions. Mostly.",
              "Three decades of doing whatever I want. Not stopping now.",
              "This is 30. And 30 looks expensive.",
              "I didn't peak yet. I'm still climbing.",
            ],
          },
          {
            name: "Soft & Reflective",
            captions: [
              "30 years of becoming someone I'm proud of.",
              "This chapter feels different. Quieter. Better.",
              "Turning 30 and finally at peace with the timeline.",
              "Not rushing. Not behind. Just here.",
              "Thirty feels like the first age I actually chose.",
            ],
          },
          {
            name: "Funny & Real",
            captions: [
              "30. My back hurts and I have opinions about mattresses now.",
              "Officially too old to pretend I like going out after 10pm.",
              "They say 30 is the new 20 but my knees disagree.",
              "I'm 30. I bring Tupperware to parties. This is who I am now.",
              "Three decades in and I still don't know what I want for dinner.",
            ],
          },
          {
            name: "Luxury & Glamour",
            captions: [
              "30 and the taste has only gotten more expensive.",
              "This birthday is giving main character with a black card.",
              "Flirty thirty. Private table. No plus ones.",
              "Thirty looks like champagne problems and designer solutions.",
              "I turned 30 the way I plan to live it — lavishly.",
            ],
          },
          {
            name: "Grateful & Grounded",
            captions: [
              "Grateful doesn't even cover it. 30 years deep and I'm still here.",
              "Not everyone gets to turn 30. I don't take that lightly.",
              "This birthday is for the people who showed up. You know who you are.",
              "30 years of lessons, losses, and the kind of love that stays.",
              "I made it to 30 with my peace intact. That's the flex.",
            ],
          },
        ],
      },
      {
        type: "tip-list",
        heading: "How to Pick the Right 30th Birthday Caption",
        tips: [
          { title: "Match the vibe, not the trend", body: "If your birthday is intimate, don't force a hype caption. The best ones feel true." },
          { title: "Short usually wins", body: "Most people stop reading after the first line. Lead with the strongest sentence." },
          { title: "Don't over-hashtag", body: "Two or three relevant hashtags is enough. #blessed isn't doing what you think it is." },
        ],
      },
      { type: "cta", headline: "Want captions made just for you?", subheadline: "Our birthday generator creates a personalized caption pack based on your vibe, zodiac sign, and celebration style.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "21st-birthday-captions",
    category: "captions",
    title: "21st Birthday Captions for Instagram (2026) — Finally Legal & Living",
    description: "21st birthday Instagram captions that match your energy — hype, funny, classy, luxe, and everything in between. Copy and post.",
    headline: "21st Birthday Captions for Instagram",
    subheadline: "Twenty-one. Legal everywhere. Unbothered always.",
    tags: { age: 21 },
    canonicalPath: "/birthday-captions/21st-birthday-captions",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "21st Birthday Captions for Instagram", subheadline: "Twenty-one. Legal everywhere. Unbothered always." },
      { type: "paragraph", body: "Twenty-one is the birthday where you officially arrive. Not just legally — energetically. It's the first birthday that feels like it belongs to you and not your parents. Whether you're going out, staying in, or doing something you'll half-remember by morning, the caption should match the moment. We wrote these so you can focus on the celebration." },
      {
        type: "caption-list",
        heading: "The Best 21st Birthday Captions",
        categories: [
          { name: "Hype & Confident", captions: [
            "21 and I'm doing everything they said I couldn't.",
            "Finally legal. Still unmanageable.",
            "21 candles and I'm still the brightest thing in the room.",
            "This is the year I stop asking permission.",
            "Twenty-one years in the making. Worth the wait.",
          ]},
          { name: "Funny & Real", captions: [
            "I've been practicing for this birthday for years. Illegally.",
            "21. My liver just sent a resignation letter.",
            "I can officially complain about hangovers out loud now.",
            "Plot twist: I still can't cook. But I can drink wine about it.",
            "Cheers to 21 years of my parents pretending I'm easy to raise.",
          ]},
          { name: "Soft & Classy", captions: [
            "21 and learning that the best things come quietly.",
            "Not the loudest in the room. Just the most unforgettable.",
            "Cheers to 21 years of figuring out what matters.",
            "Growing up is overrated but growing into yourself isn't.",
            "Twenty-one and choosing peace every time.",
          ]},
          { name: "Luxury & Glamour", captions: [
            "21 looks like first class. Even when I can barely afford economy.",
            "This birthday is sponsored by taste I can't yet fund.",
            "Twenty-one and already too refined for this timeline.",
            "The aesthetic is expensive. The budget is creative.",
          ]},
          { name: "Mystical & Zodiac", captions: [
            "21 trips around the sun and every orbit hit different.",
            "The universe didn't make me easy. She made me interesting.",
            "Born for this. Literally. The stars said so.",
          ]},
        ],
      },
      { type: "tip-list", heading: "21st Birthday Caption Tips", tips: [
        { title: "Lead with your age", body: "21 is iconic. Put the number front and center — it does the work for you." },
        { title: "Don't overthink the legal jokes", body: "Everyone makes them. The good ones are short and self-aware, not a whole paragraph about wine." },
        { title: "Match the energy of the photo", body: "A glam shot needs a glam caption. A candid with friends needs something warmer. Don't mismatch." },
      ]},
      { type: "cta", headline: "Get captions made for your 21st", subheadline: "Our generator creates personalized captions based on your vibe, zodiac sign, and who you're becoming at 21.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "25th-birthday-captions",
    category: "captions",
    title: "25th Birthday Captions for Instagram (2026) — Quarter Century Energy",
    description: "25th birthday captions for every mood — hype, reflective, funny, luxe, and main character energy. Copy and post.",
    headline: "25th Birthday Captions for Instagram",
    subheadline: "Quarter century. Full momentum.",
    tags: { age: 25 },
    canonicalPath: "/birthday-captions/25th-birthday-captions",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "25th Birthday Captions for Instagram", subheadline: "Quarter century. Full momentum." },
      { type: "paragraph", body: "Twenty-five is the age where you stop explaining yourself and start just being yourself. It's not a milestone anyone throws you a party for — but it should be. You're past the phase of pretending and entering the phase of knowing. These captions are for the version of you that's done warming up." },
      {
        type: "caption-list",
        heading: "The Best 25th Birthday Captions",
        categories: [
          { name: "Hype & Confident", captions: [
            "Quarter century and I already know the blueprint.",
            "25 and every year keeps getting louder.",
            "A whole quarter century of main character energy.",
            "25. Not the final form. Just the best one so far.",
            "A quarter century of showing up. Not stopping now.",
          ]},
          { name: "Soft & Reflective", captions: [
            "25 years in and I'm finally becoming who I was always supposed to be.",
            "This is the age where everything starts to click.",
            "Not where I planned to be. Somewhere better.",
            "Twenty-five taught me that peace is not passive. It's chosen.",
            "Quarter century of lessons. Finally listening.",
          ]},
          { name: "Funny & Real", captions: [
            "25. Halfway to 50 and fully in denial.",
            "My car insurance goes down this year. That's the real birthday gift.",
            "Quarter life crisis? No. Quarter life glow up.",
            "I'm 25 and I still call my mom when I hear a weird noise.",
            "Twenty-five and my idea of a party is sleeping in.",
          ]},
          { name: "Luxury & Glamour", captions: [
            "25 and the taste is getting expensive. Good.",
            "Quarter century of refinement. The next 25 are the payoff.",
            "This birthday is an investment in a very specific lifestyle.",
            "Twenty-five looks like the first draft of expensive.",
          ]},
          { name: "Mystical & Zodiac", captions: [
            "25 revolutions around the sun and I'm still in orbit.",
            "The stars aligned 25 years ago. They haven't stopped since.",
            "A quarter century of cosmic intention. This year hits different.",
          ]},
        ],
      },
      { type: "tip-list", heading: "25th Birthday Caption Tips", tips: [
        { title: "Own the quarter-century angle", body: "25 is the only age where the fraction works as a flex. Use it." },
        { title: "Reflective hits harder at 25", body: "You're old enough to have real stories. A reflective caption at 25 lands better than at 21." },
        { title: "Keep it under two sentences", body: "The best 25th birthday captions are punchy. Save the essay for the journal." },
      ]},
      { type: "cta", headline: "Want captions written for your quarter century?", subheadline: "Our generator creates personalized captions based on your vibe, zodiac sign, and turning 25 energy.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "40th-birthday-captions",
    category: "captions",
    title: "40th Birthday Captions for Instagram (2026) — Fabulous at Forty",
    description: "40th birthday Instagram captions for the person who's only getting better. Hype, luxe, funny, wise, and unapologetic.",
    headline: "40th Birthday Captions for Instagram",
    subheadline: "Forty and finally unbothered.",
    tags: { age: 40 },
    canonicalPath: "/birthday-captions/40th-birthday-captions",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-12",
    sections: [
      { type: "hero", headline: "40th Birthday Captions for Instagram", subheadline: "Forty and finally unbothered." },
      { type: "paragraph", body: "Forty is when people stop performing and start living. It's the birthday where you already know what you like, who you love, and what you're done tolerating. Your caption should reflect that. Not a midlife crisis — a midlife clarity. These are for the person who's done warming up and is finally playing their song." },
      {
        type: "caption-list",
        heading: "The Best 40th Birthday Captions",
        categories: [
          { name: "Confident & Powerful", captions: [
            "40 looks like knowing exactly what I bring to the table.",
            "Four decades of refinement. You can't rush this.",
            "40 is when you stop apologizing for being yourself. Finally.",
            "I didn't arrive at 40. I was built for it.",
            "Forty and every room I walk into is better for it.",
          ]},
          { name: "Funny & Real", captions: [
            "40. I now consider 9pm a late night.",
            "Officially old enough to say 'back in my day' without irony.",
            "My 20s were chaotic, my 30s were growth, my 40s are revenge.",
            "I'm 40 and I have opinions about thread count now.",
            "Forty. The age where you stop pretending to like things.",
          ]},
          { name: "Luxury & Glamour", captions: [
            "Forty looks expensive because it is.",
            "This decade is giving quiet luxury and loud confidence.",
            "40 years of taste. The bill reflects it.",
            "Four decades of earning this. The view from here is worth it.",
          ]},
          { name: "Soft & Grateful", captions: [
            "40 years of being loved by people who actually showed up.",
            "Forty and I finally understand that peace is the real luxury.",
            "Not everyone makes it to 40 with their spirit intact. I'm grateful.",
            "This birthday is quieter than the rest. That's the point.",
          ]},
          { name: "Wise & Unbothered", captions: [
            "40 is the age where your silence says more than your words ever did.",
            "Four decades of learning when to speak and when to walk away.",
            "Forty and I've stopped explaining myself to people who don't listen.",
          ]},
        ],
      },
      { type: "tip-list", heading: "40th Birthday Caption Tips", tips: [
        { title: "Lean into authority", body: "At 40, confidence reads as earned, not arrogant. Don't soften it." },
        { title: "Humor works when it's self-aware", body: "The best 40th birthday jokes are about knowing yourself better, not about getting old." },
        { title: "Short and decisive wins", body: "Forty-year-olds don't need a paragraph. One strong line hits harder." },
      ]},
      { type: "cta", headline: "Get captions crafted for your 40th", subheadline: "Our generator creates a personalized caption pack based on four decades of you.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "35th-birthday-captions",
    category: "captions",
    title: "35th Birthday Captions for Instagram (2026) — Midway and Magnificent",
    description: "35th birthday Instagram captions for the person who's done apologizing — confident, funny, luxe, reflective, and real.",
    headline: "35th Birthday Captions for Instagram",
    subheadline: "Thirty-five. The quiet flex.",
    tags: { age: 35 },
    canonicalPath: "/birthday-captions/35th-birthday-captions",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "35th Birthday Captions for Instagram", subheadline: "Thirty-five. The quiet flex." },
      { type: "paragraph", body: "Thirty-five doesn't get the hype of 30 or the milestone weight of 40 — and that's exactly why it's powerful. It's the age where you've stopped performing and started arriving. No one's throwing you a surprise party, but you don't need one. You already know what you want. These captions are for the person who's done explaining and started just being." },
      {
        type: "caption-list",
        heading: "The Best 35th Birthday Captions",
        categories: [
          { name: "Confident & Arrived", captions: [
            "35. I stopped explaining. Start observing.",
            "Halfway to 70 and I've never been sharper.",
            "35 and I know exactly who gets my energy. And who doesn't.",
            "This is the age where quiet confidence becomes loud results.",
            "Thirty-five doesn't need a spotlight. It is the spotlight.",
          ]},
          { name: "Soft & Reflective", captions: [
            "35 years of becoming. Still not done.",
            "This age feels like the first one I actually chose for myself.",
            "Thirty-five and the peace is louder than the noise ever was.",
            "I used to chase moments. Now they find me.",
            "The best version of me started showing up around 33. At 35, she's settled in.",
          ]},
          { name: "Funny & Real", captions: [
            "35. My hangovers now require a recovery plan and a full day.",
            "Officially closer to 40 than 30 and I'm pretending that's fine.",
            "I'm 35 and my idea of a wild night is staying up past 11.",
            "Thirty-five: the age where you finally understand why your parents were tired.",
            "I Googled 'mid-30s birthday caption' and realized I am the demographic now.",
          ]},
          { name: "Luxury & Elevated", captions: [
            "35 and the taste keeps getting more expensive. As it should.",
            "This is the birthday where quality replaced quantity in everything.",
            "Thirty-five looks like knowing your worth and adding tax.",
            "The 30s are for building. 35 is where you start to see the view.",
          ]},
          { name: "Grounded & Grateful", captions: [
            "35 years of proof that I can handle whatever comes.",
            "Not everyone makes it to 35 with their joy intact. I did.",
            "This birthday is for the version of me that kept going when it was hard.",
          ]},
        ],
      },
      { type: "tip-list", heading: "35th Birthday Caption Tips", tips: [
        { title: "Don't try to sound 25", body: "The best 35th captions come from knowing who you are, not from trying to recapture who you were." },
        { title: "Understated confidence hits hardest", body: "At 35, the flex is subtle. One quiet line beats three loud ones." },
        { title: "Reference the in-between", body: "35 lives between two milestones. Leaning into that middle space is what makes these captions feel authentic." },
      ]},
      { type: "cta", headline: "Get captions written for your 35th", subheadline: "Our generator creates a personalized caption pack based on your vibe, zodiac sign, and the energy of 35.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "50th-birthday-captions",
    category: "captions",
    title: "50th Birthday Captions for Instagram (2026) — Half a Century, Fully Arrived",
    description: "50th birthday Instagram captions — celebratory, elegant, funny, powerful, and grateful. For the person who earned every year.",
    headline: "50th Birthday Captions for Instagram",
    subheadline: "Fifty. Not a finish line — a vantage point.",
    tags: { age: 50 },
    canonicalPath: "/birthday-captions/50th-birthday-captions",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "50th Birthday Captions for Instagram", subheadline: "Fifty. Not a finish line — a vantage point." },
      { type: "paragraph", body: "Fifty is the birthday that earns its own gravity. It's not young. It's not old. It's the age where your presence in a room speaks before you do. Whether you're throwing a party, taking a trip, or posting a photo that says 'I'm still here and I'm still this,' your caption should carry the weight of someone who's earned every line on their face and every lesson behind it." },
      {
        type: "caption-list",
        heading: "The Best 50th Birthday Captions",
        categories: [
          { name: "Powerful & Celebratory", captions: [
            "Half a century. Full power.",
            "50 is not a number. It's a resume.",
            "I've spent 50 years becoming someone I'd want to know. I succeeded.",
            "Fifty and the best compliment anyone gives me is 'you haven't changed.' I have. I'm better.",
            "This is what 50 looks like when you didn't let life harden you.",
          ]},
          { name: "Elegant & Refined", captions: [
            "50 and every room I walk into is better for it.",
            "Five decades of showing up. The world noticed.",
            "At 50, elegance isn't something you put on. It's something you've become.",
            "Fifty is the age where your standards finally match your taste.",
          ]},
          { name: "Funny & Self-Aware", captions: [
            "50. I now require reading glasses to read my own birthday captions.",
            "Half a century old and I still don't know what I want for dinner.",
            "I'm 50 and my back goes out more than I do.",
            "Fifty: the age where 'let me check my calendar' means 'let me check my energy.'",
            "I've survived five decades. At this point I'm basically immortal.",
          ]},
          { name: "Grateful & Wise", captions: [
            "50 years of being loved by people I didn't always deserve.",
            "Every year after this is bonus. And I plan to spend the bonus well.",
            "Not everyone gets to turn 50. I don't take a single day for granted.",
            "Fifty taught me that the things that matter most are never the things you bought.",
          ]},
          { name: "Legacy & Impact", captions: [
            "50 isn't about what I've done. It's about what I've built that outlasts me.",
            "Half a century of seeds planted. Now I sit in the shade.",
            "At 50, you stop counting years and start counting impact.",
          ]},
        ],
      },
      { type: "tip-list", heading: "50th Birthday Caption Tips", tips: [
        { title: "Lead with earned authority", body: "At 50, you don't need permission to be confident. The caption should sound like someone who's been right more than they've been wrong." },
        { title: "Don't age-shame yourself for laughs", body: "The best 50th humor is self-aware, not self-deprecating. 'I'm old' jokes are tired. 'I'm experienced' jokes land better." },
        { title: "Keep it timeless", body: "The best 50th captions sound like they could be carved into stone. Write one that still works in 10 years." },
      ]},
      { type: "cta", headline: "Get captions written for your 50th", subheadline: "Our generator creates a personalized caption pack that matches five decades of you.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-captions-for-best-friend",
    category: "captions",
    title: "Birthday Captions for Best Friend (2026) — What to Post for Your Person",
    description: "Birthday captions for your best friend — funny, sentimental, hype, short, and real. For the person who deserves more than 'happy birthday.'",
    headline: "Birthday Captions for Your Best Friend",
    subheadline: "For the person who already knows what you'd say. Now post it.",
    tags: { celebrationType: "social-post" },
    canonicalPath: "/birthday-captions/birthday-captions-for-best-friend",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Birthday Captions for Your Best Friend", subheadline: "For the person who already knows what you'd say. Now post it." },
      { type: "paragraph", body: "Posting for your best friend's birthday is one of those moments where you want the caption to sound exactly like you — not like a greeting card. The best friend birthday post is half inside joke, half genuine love, and fully something they'll screenshot. These captions are written for the person who matters enough to make you draft four versions before posting." },
      {
        type: "caption-list",
        heading: "Birthday Captions for Your Best Friend",
        categories: [
          { name: "Hype & Celebratory", captions: [
            "It's my best friend's birthday and the world should be grateful she exists.",
            "Everyone wish my person the happiest birthday or I'm taking it personally.",
            "Today belongs to the person who made every bad decision with me and every good memory because of me.",
            "The main character of my life just leveled up. Happy birthday to the one.",
            "If you don't know her, you're missing out. If you do, you already know.",
          ]},
          { name: "Funny & Real", captions: [
            "Happy birthday to the only person who's seen me at my worst and didn't leave. Yet.",
            "Another year of me being the funny one and you being the pretty one. The balance is important.",
            "We've been friends long enough that I have leverage. Happy birthday. Don't test me.",
            "Happy birthday to my emergency contact, therapist, and hype man. You're not getting a raise.",
            "I'd write something sentimental but we'd both cringe. So here's a photo where we look hot. Happy birthday.",
          ]},
          { name: "Sentimental & Real", captions: [
            "You're the friend who made me believe I'm worth showing up for. Happy birthday to my proof.",
            "Every version of me has loved every version of you. Happy birthday to my constant.",
            "You've held space for me in ways I'm still learning to name. Today I hold space for you. Happy birthday.",
            "The world gave me a lot of things I didn't ask for. But you — I'd choose you every time.",
            "Happy birthday to the person who knows me without the performance. That's rare. You're rare.",
          ]},
          { name: "Short & Punchy", captions: [
            "My person. Their day. That's it.",
            "She said it's her birthday. So we celebrate. No questions.",
            "Happy birthday to my favorite human on this planet. Sorry to everyone else.",
            "You already know what you mean to me. Happy birthday.",
          ]},
          { name: "For the Group Post", captions: [
            "This is the friend everyone needs and only I got. Happy birthday.",
            "Years of friendship. Thousands of hours on the phone. One perfect human. Happy birthday.",
            "I don't post people often. But this one earned every pixel. Happy birthday.",
          ]},
        ],
      },
      { type: "tip-list", heading: "Best Friend Birthday Caption Tips", tips: [
        { title: "Write it like a text, not a speech", body: "The best friend birthday caption should sound like something you'd actually say to them. If it sounds like a toast at a wedding, tone it down." },
        { title: "Pick the photo that tells the story", body: "The caption doesn't carry the whole weight. Choose the photo that shows who you are together — then let the caption land the punchline." },
        { title: "Don't overthink the length", body: "One perfect sentence beats three mediocre paragraphs. If you can say it in one line, do it." },
      ]},
      { type: "cta", headline: "Get captions made for your birthday", subheadline: "Our generator creates a personalized caption pack based on your vibe, zodiac, and celebration energy.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
  {
    slug: "birthday-captions-for-yourself",
    category: "captions",
    title: "Birthday Captions for Yourself (2026) — What to Post on Your Own Birthday",
    description: "Birthday captions for your own birthday — hype, reflective, funny, luxe, and real. For the person who wants their post to match how they actually feel.",
    headline: "Birthday Captions for Yourself",
    subheadline: "Your birthday. Your post. Your rules.",
    tags: { celebrationType: "self-post" },
    canonicalPath: "/birthday-captions/birthday-captions-for-yourself",
    schemaType: "ItemList",
    publishStatus: "published",
    publishedAt: "2026-04-13",
    sections: [
      { type: "hero", headline: "Birthday Captions for Yourself", subheadline: "Your birthday. Your post. Your rules." },
      { type: "paragraph", body: "Posting for your own birthday is an art. Too humble and it sounds like you're fishing. Too bold and it sounds like you're performing. The best self-birthday caption lands in the middle — confident, honest, and unapologetically you. These captions are for the person who wants their birthday post to feel like a statement, not an announcement." },
      {
        type: "caption-list",
        heading: "Birthday Captions for Your Own Day",
        categories: [
          { name: "Main Character Energy", captions: [
            "Another year of being exactly who I said I'd be.",
            "It's my birthday and the only person I need to impress is me.",
            "Born today. Been winning since.",
            "My birthday is a national holiday in my household and that's enough.",
            "The lead character doesn't announce the episode. She just shows up.",
          ]},
          { name: "Soft & Grateful", captions: [
            "Another year of learning that the quiet wins matter most.",
            "Grateful doesn't cover it. But it's where I'll start.",
            "This birthday is for the version of me that didn't give up.",
            "I made it to another year with my peace intact. That's the celebration.",
            "Quiet birthday. Full heart. No complaints.",
          ]},
          { name: "Funny & Honest", captions: [
            "It's my birthday. I will be accepting compliments and carbs only.",
            "Another year older and still Googling things I should probably already know.",
            "Happy birthday to me. I'm my own best gift and worst financial advisor.",
            "Aging gracefully is a scam. I'm aging chaotically and it's going great.",
            "It's my birthday and I'm choosing to believe I don't look my age.",
          ]},
          { name: "Luxury & Unbothered", captions: [
            "My birthday, my standards, my table for one if necessary.",
            "This birthday is sponsored by taste I've spent years developing.",
            "I celebrate myself the way I live: intentionally and expensively.",
            "Today is about me. Tomorrow can be about everyone else.",
          ]},
          { name: "Short & Powerful", captions: [
            "Still here. Still that.",
            "My day. My energy. My year.",
            "Born for this. All of it.",
            "Grateful, growing, going.",
          ]},
        ],
      },
      { type: "tip-list", heading: "Self-Birthday Caption Tips", tips: [
        { title: "Don't apologize for posting", body: "It's your birthday. You're allowed to celebrate yourself publicly. Don't start with 'I know I don't usually post but...' Just post." },
        { title: "Pick the photo first, then write", body: "The caption should match the energy of the photo. A glam shot needs confidence. A candid needs warmth. Don't mismatch." },
        { title: "One perfect line beats three average ones", body: "The best self-birthday captions are short. If you can say it in one sentence, do." },
      ]},
      { type: "cta", headline: "Get captions made just for you", subheadline: "Our generator creates a personalized caption pack based on your age, vibe, zodiac, and celebration energy.", buttonText: "Generate My Birthday", buttonHref: "/onboarding" },
      { type: "related-content" },
    ],
  },
];

captionPages.forEach(registerPage);
